/* Preamble: 
	Decompiled Web Assembly generated by wasmdec.
	Note: this section of code isn't decompiled webassembly,
	just support functions in cased decompiled code requires it

*/
#include <stdint.h> // For the bit size specific types
#include <math.h> // For certian WASM operations
typedef const char* wasm_table_t; // WASM tables
// Bit size specific types not declared in stdint.h:
typedef float float32_t;
typedef double float64_t;
// C implementation of WASM expressions:
unsigned int _rotl(const unsigned int value, int shift) {
	if ((shift &= sizeof(value) * 8 - 1) == 0)
		return value;
	return (value << shift) | (value >> (sizeof(value)*8 - shift));
}
unsigned int _rotr(const unsigned int value, int shift) {
	if ((shift &= sizeof(value) * 8 - 1) == 0)
		return value;
	return (value >> shift) | (value << (sizeof(value)*8 - shift));
}
#define MAX(a,b) ((a) > (b) ? a : b)
#define MIN(a,b) ((a) < (b) ? a : b)
// Host functions: used to request information from host machine.
extern int32_t host_has_feature(int32_t feature_opcode);
extern void host_grow_memory(int32_t size);
extern int32_t host_get_current_memory(void);
extern int32_t host_get_page_size(void);
// End of preamble

// WASM globals:
int global$0 = 5246768;
const int global$1 = 3888;
int global$2 = 0;

extern void ffimport$0(int local0); /* import */
extern void ffimport$1(int local0); /* import */
extern int ffimport$2(int local0, int local1, int local2, int local3); /* import */
extern int ffimport$3(int local0, int local1, int local2); /* import */
extern int ffimport$4(int local0); /* import */
extern void ffimport$5(); /* import */
extern void ffimport$6(int local0); /* import */
int f0() {
3888}
void f1() {
}
int f2() {
	// Parsed WASM function locals:
	int local0; 
	local0 = 2;
	return local0;
}
int f3() {
	// Parsed WASM function locals:
	int local0; 
	local0 = 1;
	return local0;
}
int f4() {
	// Parsed WASM function locals:
	int local0; 
	int local1; 
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	int local11; 
	int local12; 
	int local13; 
	int local14; 
	int local15; 
	int local16; 
	int local17; 
	int local18; 
	int local19; 
	int local20; 
	int local21; 
	int local22; 
	int local23; 
	int local24; 
	int local25; 
	int local26; 
	int local27; 
	int local28; 
	int local29; 
	int local30; 
	int local31; 
	int local32; 
	int local33; 
	int local34; 
	int local35; 
	int local36; 
	int local37; 
	int local38; 
	int local39; 
	int local40; 
	int local41; 
	int local42; 
	int local43; 
	int local44; 
	int local45; 
	int local46; 
	int local47; 
	int local48; 
	int local49; 
	int local50; 
	int local51; 
	int local52; 
	int local53; 
	local0 = global$0;
local1 = 16local2 = local0 - local1	label$1:
	if (local52 = local2 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local52;
	local3 = 1024;
	local4 = 0;
	/* Drop routine */
	f9(local3, local4);
	/* End of drop routine */
	local5 = 3;
	local6 = local2 + local5;
	local7 = local6;
	/* Drop routine */
	f38(local7);
	/* End of drop routine */
	local8 = 1053;
	local9 = 0;
	/* Drop routine */
	f9(local8, local9);
	/* End of drop routine */
	local10 = 3;
	local11 = local2 + local10;
	local12 = local11;
	local13 = 1776;
	/* Drop routine */
	f8(local12, local13);
	/* End of drop routine */
	local14 = 1092;
	local15 = 0;
	/* Drop routine */
	f9(local14, local15);
	/* End of drop routine */
	local16 = 3;
	local17 = local2 + local16;
	local18 = local17;
	/* Drop routine */
	f38(local18);
	/* End of drop routine */
	local19 = 1100;
	local20 = 0;
	/* Drop routine */
	f9(local19, local20);
	/* End of drop routine */
	local21 = 	f3();
;
*((void*)(local2) = local21; 
	local22 = 1092;
	local23 = 0;
	/* Drop routine */
	f9(local22, local23);
	/* End of drop routine */
	local24 = 3;
	local25 = local2 + local24;
	local26 = local25;
	/* Drop routine */
	f38(local26);
	/* End of drop routine */
	local27 = 1131;
	local28 = 0;
	/* Drop routine */
	f9(local27, local28);
	/* End of drop routine */
	local29 = 	f2();
;
*((void*)(local2) = local29; 
	local30 = 1092;
	local31 = 0;
	/* Drop routine */
	f9(local30, local31);
	/* End of drop routine */
	local32 = 3;
	local33 = local2 + local32;
	local34 = local33;
	/* Drop routine */
	f38(local34);
	/* End of drop routine */
	local35 = 1162;
	local36 = 0;
	/* Drop routine */
	f9(local35, local36);
	/* End of drop routine */
	local37 = 3;
	local38 = local2 + local37;
	local39 = local38;
	local40 = 30;
	local41 = local39 + local40;
	/* Drop routine */
	f38(local41);
	/* End of drop routine */
	local42 = 1174;
	local43 = 0;
	/* Drop routine */
	f9(local42, local43);
	/* End of drop routine */
	local44 = 1;
	local45 = 3;
	local46 = local2 + local45;
	local47 = local46;
	local48 = 3;
	local49 = local47 + local48;
	/* Drop routine */
	f38(local49);
	/* End of drop routine */
	local50 = 16;
	local51 = local2 + local50;
	label$3:
	if (local53 = local51 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local53;
	return local44;
}
int f5() {
	// Parsed WASM function locals:
	int local0; 
	int local1; 
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	int local11; 
	int local12; 
	int local13; 
	int local14; 
	int local15; 
	int local16; 
	int local17; 
	int local18; 
	int local19; 
	int local20; 
	local0 = global$0;
local1 = 16local2 = local0 - local1	label$1:
	if (local19 = local2 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local19;
	local3 = 0;
*((void*)(local2) = local3; 
*((void*)(local2) = local3; 
	local4 = 	f4();
;
*((void*)(local2) = local4; 
	local5 = 	*(void*)(local2);
*((void*)(local2) = local5; 
	local6 = 1185;
	/* Drop routine */
	f9(local6, local2);
	/* End of drop routine */
	local7 = 1;
	local8 = 	*(void*)(local2);
	local9 = local8;
	local10 = local7;
	local11 = local9 == local10;
	local12 = 1;
	local13 = local11 & local12;
	label$3:
	if (local13 == 0) break;	local14 = 1197;
	local15 = 0;
	/* Drop routine */
	f9(local14, local15);
	/* End of drop routine */
	local16 = 0;
	local17 = 16;
	local18 = local2 + local17;
	label$4:
	if (local20 = local18 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local20;
	return local16;
}
int f6(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	local2 = 	f5();
;
	return local2;
}
int f7(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	label$1:
		label$2:
		if (local1 ^ local0 & 3) break;			label$3:
			if (local1 & 3 == 0) break;			while (1) { // Loop name: 'label$4'
*((void*)(local0) = local2 = 			*(void*)(local1)			if (local2 == 0) break;local0 = local0 + 1			if (local1 = local1 + 1 & 3) break;
		} // End of loop 'label$4'
	if (local2 = 	*(void*)(local1) ^ -1 & local2 + -16843009 & -2139062144) break;	while (1) { // Loop name: 'label$5'
*((void*)(local0) = local2local2 = 	*(void*)(local1)local0 = local0 + 4local1 = local1 + 4	if (local2 ^ -1 & local2 + -16843009 & -2139062144 == 0) break;
	} // End of loop 'label$5'
*((void*)(local0) = local2 = 	*(void*)(local1)	if (local2 == 0) break;	while (1) { // Loop name: 'label$6'
*((void*)(local0) = local2 = 	*(void*)(local1)local0 = local0 + 1local1 = local1 + 1	if (local2) break;
	} // End of loop 'label$6'
local0}
int f8(int local0, int local1) {
	/* Drop routine */
	f7(local0, local1);
	/* End of drop routine */
local0}
int f9(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	int local3; 
	int local4; 
	label$1:
	if (local3 = local2 = global$0 - 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local3;
*((void*)(local2) = local1; 
	local1 = 	f31(	*(void*)(0), local0, local1);
;
	label$3:
	if (local4 = local2 + 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local4;
local1}
int f10(int local0) {
1}
void f11(int local0) {
}
int f12() {
2272}
int f13(int local0) {
local0 + -48 < 10}
int f14() {
1880}
int f15(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	local3 = 1;
	label$1:
		label$2:
		if (local0 == 0) break;		if (local1 <= 127) break;			label$3:
				label$4:
				if (				*(void*)(				*(void*)(				f16();
))) break;				if (local1 & -128 == 57216) break;*((void*)(				f12();
) = 25				break;				label$5:
				if (local1 > 2047) break;*((void*)(local0) = local1 & 63 | 128*((void*)(local0) = local1 >> 6 | 192				return 2;
				label$6:
					label$7:
					if (local1 < 55296) break;					if (local1 & -8192 != 57344) break;*((void*)(local0) = local1 & 63 | 128*((void*)(local0) = local1 >> 12 | 224*((void*)(local0) = local1 >> 6 & 63 | 128				return 3;
				label$8:
				if (local1 + -65536 > 1048575) break;*((void*)(local0) = local1 & 63 | 128*((void*)(local0) = local1 >> 18 | 240*((void*)(local0) = local1 >> 6 & 63 | 128*((void*)(local0) = local1 >> 12 & 63 | 128				return 4;
*((void*)(			f12();
) = 25local3 = -1	return local3;
*((void*)(local0) = local11}
int f16() {
	f14();
}
int f17(int local0, int local1) {
	label$1:
	if (local0) break;	return 0;
	f15(local0, local1, 0);
}
int f18(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	local3 = local2 != 0;
	label$1:
		label$2:
			label$3:
				label$4:
				if (local2 == 0) break;				if (local0 & 3 == 0) break;local4 = local1 & 255				while (1) { // Loop name: 'label$5'
				if (				*(void*)(local0) == local4) break;local0 = local0 + 1local3 = local2 = local2 + -1 != 0				if (local2 == 0) break;				if (local0 & 3) break;
			} // End of loop 'label$5'
		if (local3 == 0) break;	if (	*(void*)(local0) == local1 & 255) break;		label$6:
			label$7:
			if (local2 < 4) break;local4 = local1 & 255 * 16843009local5 = local3 = local2 + -4 & 3local6 = local3 & -4 + local0 + 4			while (1) { // Loop name: 'label$8'
			if (local3 = 			*(void*)(local0) ^ local4 ^ -1 & local3 + -16843009 & -2139062144) break;local0 = local0 + 4			if (local2 = local2 + -4 > 3) break;
		} // End of loop 'label$8'
local2 = local5local0 = local6	if (local2 == 0) break;local3 = local1 & 255	while (1) { // Loop name: 'label$9'
	if (	*(void*)(local0) == local3) break;local0 = local0 + 1	if (local2 = local2 + -1) break;
	} // End of loop 'label$9'
	return 0;
local0}
double f19(double local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	long local3; 
	label$1:
	if (local2 = (int)local3 = (long)local0 >> 52 & 2047 == 2047) break;		label$2:
		if (local2) break;			label$3:
				label$4:
				if (local0 != 0.000000) break;local2 = 0				break;local0 = 			f19(local0 * 18446744073709551616.000000, local1);
local2 = 			*(void*)(local1) + -64*((void*)(local1) = local2		return local0;
*((void*)(local1) = local2 + -1022local0 = (double)local3 & -9218868437227405313 | 4602678819172646912local0}
int f20(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	label$1:
		label$2:
		if (local3 = 		*(void*)(local2)) break;local4 = 0		if (		f37(local2);
) break;local3 = 		*(void*)(local2)		label$3:
		if (local3 - local5 = 		*(void*)(local2) >= local1) break;		return // Indirect call:
(		*(void*)(local2))(local2, local0, local1); 
;
local6 = 0		label$4:
		if (		*(void*)(local2) < 0) break;local4 = local1		while (1) { // Loop name: 'label$5'
		if (local3 = local4 == 0) break;		if (		*(void*)(local0 + local4 = local3 + -1) != 10) break;
	} // End of loop 'label$5'
	if (local4 = // Indirect call:
(	*(void*)(local2))(local2, local0, local3); 
 < local3) break;local1 = local1 - local3local0 = local0 + local3local5 = 	*(void*)(local2)local6 = local3	/* Drop routine */
	f49(local5, local0, local1);
	/* End of drop routine */
*((void*)(local2) = 	*(void*)(local2) + local1local4 = local6 + local1local4}
int f21(int local0, int local1, int local2, int local3) {
	// Parsed WASM function locals:
	int local4; 
	int local5; 
	local4 = local2 * local1;
	label$1:
		label$2:
		if (		*(void*)(local3) > -1) break;local0 = 		f20(local0, local4, local3);
		break;local5 = 	f10(local3);
local0 = 	f20(local0, local4, local3);
	if (local5 == 0) break;	f11(local3);
	label$3:
	if (local0 != local4) break;	return (local1) ? (local2) : (0);
;
local0 / local1}
int f22(int local0, int local1, int local2, int local3, int local4) {
	// Parsed WASM function locals:
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	label$1:
	if (local8 = local5 = global$0 - 208 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local8;
*((void*)(local5) = local2; 
	local2 = 0;
	/* Drop routine */
	f50(local5 + 160, 0, 40);
	/* End of drop routine */
	*((void*)(local5) = 	*(void*)(local5); 
	label$3:
		label$4:
		if (		f23(0, local1, local5 + 200, local5 + 80, local5 + 160, local3, local4);
 >= 0) break;		local1 = -1;
		break;		label$5:
		if (		*(void*)(local0) < 0) break;		local2 = 		f10(local0);
;
	local6 = 	*(void*)(local0);
		label$6:
		if (		*(void*)(local0) > 0) break;		*((void*)(local0) = local6 & -33; 
	local6 = local6 & 32;
		label$7:
			label$8:
			if (			*(void*)(local0) == 0) break;			local1 = 			f23(local0, local1, local5 + 200, local5 + 80, local5 + 160, local3, local4);
;
			break;*((void*)(local0) = 80; 
		*((void*)(local0) = local5 + 80; 
*((void*)(local0) = local5; 
*((void*)(local0) = local5; 
		local7 = 		*(void*)(local0);
*((void*)(local0) = local5; 
		local1 = 		f23(local0, local1, local5 + 200, local5 + 80, local5 + 160, local3, local4);
;
		if (local7 == 0) break;	/* Drop routine */
// Indirect call:
(		*(void*)(local0))(local0, 0, 0); 
	/* End of drop routine */
*((void*)(local0) = 0; 
*((void*)(local0) = local7; 
*((void*)(local0) = 0; 
*((void*)(local0) = 0; 
		local3 = 		*(void*)(local0);
*((void*)(local0) = 0; 
		local1 = (local3) ? (local1) : (-1);
;
	*((void*)(local0) = 	local3 = 	*(void*)(local0);
 | local6; 
	local1 = (local3 & 32) ? (-1) : (local1);
;
	if (local2 == 0) break;	f11(local0);
	label$9:
	if (local9 = local5 + 208 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local9;
local1}
int f23(int local0, int local1, int local2, int local3, int local4, int local5, int local6) {
	// Parsed WASM function locals:
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	int local11; 
	int local12; 
	int local13; 
	int local14; 
	int local15; 
	int local16; 
	int local17; 
	int local18; 
	int local19; 
	int local20; 
	int local21; 
	int local22; 
	int local23; 
	long local24; 
	label$1:
	if (local22 = local7 = global$0 - 80 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local22;
*((void*)(local7) = local1; 
	local8 = local7 + 55;
	local9 = local7 + 56;
	local10 = 0;
	local11 = 0;
	local1 = 0;
	label$3:
	while (1) { // Loop name: 'label$4'
		label$5:
		if (local11 < 0) break;			label$6:
			if (local1 <= 2147483647 - local11) break;*((void*)(			f12();
) = 61; 
			local11 = -1;
			break;		local11 = local1 + local11;
	local1 = 	local12 = 	*(void*)(local7);
		label$7:
			label$8:
				label$9:
					label$10:
						label$11:
							label$12:
								label$13:
									label$14:
										label$15:
											label$16:
												label$17:
													label$18:
														label$19:
															label$20:
																label$21:
																if (																local13 = 																*(void*)(local12);
 == 0) break;																	label$22:
																	while (1) { // Loop name: 'label$23'
																		label$24:
																			label$25:
																				label$26:
																				if (																				local13 = local13 & 255;
) break;																				local13 = local1;
																				break;																			if (local13 != 37) break;																			local13 = local1;
																			while (1) { // Loop name: 'label$27'
																			if (																			*(void*)(local1) != 37) break;																			*((void*)(local7) = 																			local14 = local1 + 2;
																			local13 = local13 + 1;
																			local15 = 																			*(void*)(local1);
																			local1 = local14;
																			if (local15 == 37) break;
																		} // End of loop 'label$27'
																	local1 = local13 - local12;
																		label$28:
																		if (local0 == 0) break;																		f24(local0, local12, local1);
																	if (local1) break;																	local14 = 																	f13(																	*(void*)(																	*(void*)(local7)));
;
																	local16 = -1;
																	local13 = 1;
																	local1 = 																	*(void*)(local7);
																		label$29:
																		if (local14 == 0) break;																		if (																		*(void*)(local1) != 36) break;																		local16 = 																		*(void*)(local1) + -48;
																		local10 = 1;
																		local13 = 3;
																	*((void*)(local7) = 																	local1 = local1 + local13;
																	local13 = 0;
																		label$30:
																			label$31:
																			if (																			local15 = 																			local17 = 																			*(void*)(local1);
 + -32;
 <= 31) break;																			local14 = local1;
																			break;																		local14 = local1;
																		if (																		local15 = 1 << local15;
 & 75913 == 0) break;																		while (1) { // Loop name: 'label$32'
																		*((void*)(local7) = 																		local14 = local1 + 1;
																		local13 = local15 | local13;
																		if (																		local15 = 																		local17 = 																		*(void*)(local1);
 + -32;
 > 31) break;																		local1 = local14;
																		if (																		local15 = 1 << local15;
 & 75913) break;
																	} // End of loop 'label$32'
																	label$33:
																		label$34:
																		if (local17 != 42) break;																			label$35:
																				label$36:
																				if (																				f13(																				*(void*)(local14));
 == 0) break;																				if (																				*(void*)(																				local14 = 																				*(void*)(local7);
) != 36) break;*((void*)(																				*(void*)(local14) << 2 + local4 + -192) = 10; 
																				local1 = local14 + 3;
																				local18 = 																				*(void*)(																				*(void*)(local14) << 3 + local3 + -384);
																				local10 = 1;
																				break;																			if (local10) break;																			local10 = 0;
																			local18 = 0;
																				label$37:
																				if (local0 == 0) break;																				*((void*)(local2) = 																				local1 = 																				*(void*)(local2);
 + 4; 
																				local18 = 																				*(void*)(local1);
																			local1 = 																			*(void*)(local7) + 1;
*((void*)(local7) = local1; 
																		if (local18 > -1) break;																		local18 = 0 - local18;
																		local13 = local13 | 8192;
																		break;																	if (																	local18 = 																	f25(local7 + 76);
;
 < 0) break;																	local1 = 																	*(void*)(local7);
																local19 = -1;
																	label$38:
																	if (																	*(void*)(local1) != 46) break;																		label$39:
																		if (																		*(void*)(local1) != 42) break;																			label$40:
																			if (																			f13(																			*(void*)(local1));
 == 0) break;																			if (																			*(void*)(																			local1 = 																			*(void*)(local7);
) != 36) break;*((void*)(																			*(void*)(local1) << 2 + local4 + -192) = 10; 
																			local19 = 																			*(void*)(																			*(void*)(local1) << 3 + local3 + -384);
																			*((void*)(local7) = 																			local1 = local1 + 4;
																			break;																		if (local10) break;																			label$41:
																				label$42:
																				if (local0) break;																				local19 = 0;
																				break;																			*((void*)(local2) = 																			local1 = 																			*(void*)(local2);
 + 4; 
																			local19 = 																			*(void*)(local1);
																		*((void*)(local7) = 																		local1 = 																		*(void*)(local7) + 2;
																		break;																	*((void*)(local7) = local1 + 1; 
																	local19 = 																	f25(local7 + 76);
;
																	local1 = 																	*(void*)(local7);
																local14 = 0;
																while (1) { // Loop name: 'label$43'
																local15 = local14;
																local20 = -1;
																if (																*(void*)(local1) + -65 > 57) break;																*((void*)(local7) = 																local17 = local1 + 1;
																local14 = 																*(void*)(local1);
																local1 = local17;
																if (																local14 = 																*(void*)(local14 + local15 * 58 + 1183);
 + -1 < 8) break;
															} // End of loop 'label$43'
															if (local14 == 0) break;																label$44:
																	label$45:
																		label$46:
																			label$47:
																			if (local14 != 19) break;																			local20 = -1;
																			if (local16 <= -1) break;																			break;																		if (local16 < 0) break;*((void*)(local4 + local16 << 2) = local14; 
																		*((void*)(local7) = 																		*(void*)(local3 + local16 << 3); 
																	local1 = 0;
																	if (local0 == 0) break;																	break;																if (local0 == 0) break;																f26(local7 + 64, local14, local2, local6);
																local17 = 																*(void*)(local7);
															local13 = (local13 & 8192) ? (															local21 = local13 & -65537;
) : (local13);
;
															local20 = 0;
															local16 = 1220;
															local14 = local9;
															if (															local17 = 															local1 = (local15) ? ((local1 & 15 == 3) ? (															local1 = 															*(void*)(local17 + -1);
 & -33) : (local1);
) : (local1);
;
 + -88;
 <= 32) break;																label$48:
																	label$49:
																		label$50:
																			label$51:
																				label$52:
																				if (																				local15 = local1 + -65;
 <= 6) break;																				if (local1 != 83) break;																				if (local19 == 0) break;																				local14 = 																				*(void*)(local7);
																				break;																			switch (local14) {
																				case 1:
																					goto label$19;
																				case 2:
																					goto label$8;
																				case 3:
																					goto label$50;
																				case 4:
																					goto label$8;
																				case 5:
																					goto label$19;
																				case 6:
																					goto label$19;
																				case 7:
																					goto label$19;
																				default:
																					goto label$19;
																			}
																		local1 = 0;
																		f27(local0, 32, local18, 0, local13);
																		break;*((void*)(local7) = 0; 
																	*((void*)(local7) = 																	*(void*)(local7); 
																	*((void*)(local7) = local7 + 8; 
																	local19 = -1;
																	local14 = local7 + 8;
																local1 = 0;
																	label$53:
																	while (1) { // Loop name: 'label$54'
																	if (																	local15 = 																	*(void*)(local14);
 == 0) break;																		label$55:
																		if (																		local12 = 																		local15 = 																		f17(local7 + 4, local15);
;
 < 0;
) break;																		if (local15 > local19 - local1) break;																		local14 = local14 + 4;
																		if (local19 > 																		local1 = local15 + local1;
) break;																		break;
																} // End of loop 'label$54'
																local20 = -1;
																if (local12) break;															f27(local0, 32, local18, local1, local13);
																label$56:
																if (local1) break;																local1 = 0;
																break;															local15 = 0;
															local14 = 															*(void*)(local7);
															while (1) { // Loop name: 'label$57'
															if (															local12 = 															*(void*)(local14);
 == 0) break;															if (															local15 = 															local12 = 															f17(local7 + 4, local12);
;
 + local15;
 > local1) break;															f24(local0, local7 + 4, local12);
															local14 = local14 + 4;
															if (local15 < local1) break;
														} // End of loop 'label$57'
													f27(local0, 32, local18, local1, local13 ^ 8192);
													local1 = (local18 > local1) ? (local18) : (local1);
;
													break;												*((void*)(local7) = 												local14 = local1 + 1;
												local13 = 												*(void*)(local1);
												local1 = local14;
												break;
											} // End of loop 'label$23'
										switch (local1) {
											case 1:
												goto label$13;
											case 2:
												goto label$8;
											case 3:
												goto label$8;
											case 4:
												goto label$8;
											case 5:
												goto label$8;
											case 6:
												goto label$8;
											case 7:
												goto label$8;
											case 8:
												goto label$8;
											case 9:
												goto label$8;
											case 10:
												goto label$19;
											case 11:
												goto label$8;
											case 12:
												goto label$17;
											case 13:
												goto label$16;
											case 14:
												goto label$19;
											case 15:
												goto label$19;
											case 16:
												goto label$19;
											case 17:
												goto label$8;
											case 18:
												goto label$16;
											case 19:
												goto label$8;
											case 20:
												goto label$8;
											case 21:
												goto label$8;
											case 22:
												goto label$8;
											case 23:
												goto label$12;
											case 24:
												goto label$15;
											case 25:
												goto label$14;
											case 26:
												goto label$8;
											case 27:
												goto label$8;
											case 28:
												goto label$18;
											case 29:
												goto label$8;
											case 30:
												goto label$11;
											case 31:
												goto label$8;
											case 32:
												goto label$8;
											case 33:
												goto label$13;
											default:
												goto label$13;
										}
									local20 = local11;
									if (local0) break;									if (local10 == 0) break;									local1 = 1;
										label$58:
										while (1) { // Loop name: 'label$59'
										if (										local13 = 										*(void*)(local4 + local1 << 2);
 == 0) break;										f26(local3 + local1 << 3, local13, local2, local6);
										local20 = 1;
										if (										local1 = local1 + 1;
 != 10) break;										break;
									} // End of loop 'label$59'
								local20 = 1;
								if (local1 >= 10) break;								while (1) { // Loop name: 'label$60'
								if (								*(void*)(local4 + local1 << 2)) break;								local20 = 1;
								local13 = local1 > 8;
								local1 = local1 + 1;
								if (local13) break;								break;
							} // End of loop 'label$60'
						local20 = -1;
						break;					local1 = // Indirect call:
(local5)(local0, 					*(void*)(local7), local18, local19, local13, local1); 
;
					break;				local20 = 0;
				local14 = (local1) ? (				local1 = 				f18(				local12 = (local1) ? (				local1 = 				*(void*)(local7);
) : (1230);
;
, 0, local19);
;
) : (local12 + local19);
;
				local13 = local21;
				local19 = (local1) ? (local1 - local12) : (local19);
;
				break;			*((void*)(local7) = 			*(void*)(local7); 
			local19 = 1;
			local12 = local8;
			local14 = local9;
			local13 = local21;
			break;			label$61:
			if (			local24 = 			*(void*)(local7);
 > -1) break;			*((void*)(local7) = 			local24 = 0 - local24;
			local20 = 1;
			local16 = 1220;
			break;			label$62:
			if (local13 & 2048 == 0) break;			local20 = 1;
			local16 = 1221;
			break;		local16 = (		local20 = local13 & 1;
) ? (1222) : (1220);
;
		break;	local12 = 	f28(	*(void*)(local7), local9);
;
	local20 = 0;
	local16 = 1220;
	if (local13 & 8 == 0) break;	local19 = (local19 > local1) ? (local19) : (	local1 = local9 - local12;
 + 1);
;
	break;	local19 = (local19 > 8) ? (local19) : (8);
;
	local13 = local13 | 8;
	local1 = 120;
	local12 = 	f29(	*(void*)(local7), local9, local1 & 32);
;
	local20 = 0;
	local16 = 1220;
	if (local13 & 8 == 0) break;	if (	*(void*)(local7) == 0) break;	local16 = local1 >> 4 + 1220;
	local20 = 2;
	break;	local1 = 0;
	if (	local13 = local15 & 255;
 > 7) break;	label$63:
	label$64:
	label$65:
		label$66:
			label$67:
				label$68:
					label$69:
					switch (local13) {
						case 1:
							goto label$69;
						case 2:
							goto label$68;
						case 3:
							goto label$67;
						case 4:
							goto label$66;
						case 5:
							goto label$65;
						case 6:
							goto label$4;
						case 7:
							goto label$64;
						case 8:
							goto label$63;
						default:
							goto label$69;
					}
*((void*)(				*(void*)(local7)) = local11; 
				break;*((void*)(			*(void*)(local7)) = local11; 
			break;		*((void*)(		*(void*)(local7)) = (long)local11; 
		break;*((void*)(	*(void*)(local7)) = local11; 
	break;*((void*)(	*(void*)(local7)) = local11; 
	break;*((void*)(	*(void*)(local7)) = local11; 
	break;	*((void*)(	*(void*)(local7)) = (long)local11; 
	break;	local20 = 0;
	local16 = 1220;
	local24 = 	*(void*)(local7);
	local12 = 	f30(local24, local9);
;
	local13 = (local19 > -1) ? (local13 & -65537) : (local13);
;
	local24 = 	*(void*)(local7);
	label$70:
	label$71:
	if (local19) break;	if (local24 == 0 == 0) break;	local19 = 0;
	local12 = local9;
	break;	local19 = (local19 > local1) ? (local19) : (	local1 = local9 - local12 + local24 == 0;
);
;
	local14 = local9;
	f27(local0, 32, 	local1 = (local18 < local14) ? (	local14 = local20 + 	local17 = (local19 < local15) ? (	local15 = local14 - local12;
) : (local19);
;
;
) : (local18);
;
, local14, local13);
	f24(local0, local16, local20);
	f27(local0, 48, local1, local14, local13 ^ 65536);
	f27(local0, 48, local17, local15, 0);
	f24(local0, local12, local15);
	f27(local0, 32, local1, local14, local13 ^ 8192);
	break;
	} // End of loop 'label$4'
	local20 = 0;
	label$72:
	if (local23 = local7 + 80 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local23;
local20}
void f24(int local0, int local1, int local2) {
	label$1:
	if (	*(void*)(local0) & 32) break;	/* Drop routine */
	f20(local1, local2, local0);
	/* End of drop routine */
}
int f25(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	int local3; 
	local1 = 0;
	label$1:
	if (	f13(	*(void*)(	*(void*)(local0)));
 == 0) break;	while (1) { // Loop name: 'label$2'
local3 = 	*(void*)(local2 = 	*(void*)(local0))*((void*)(local0) = local2 + 1local1 = local3 + local1 * 10 + -48	if (	f13(	*(void*)(local2));
) break;
	} // End of loop 'label$2'
local1}
void f26(int local0, int local1, int local2, int local3) {
	label$1:
	if (local1 > 20) break;	if (local1 = local1 + -9 > 9) break;	label$2:
		label$3:
			label$4:
				label$5:
					label$6:
						label$7:
							label$8:
								label$9:
									label$10:
										label$11:
										switch (local1) {
											case 1:
												goto label$11;
											case 2:
												goto label$10;
											case 3:
												goto label$9;
											case 4:
												goto label$8;
											case 5:
												goto label$7;
											case 6:
												goto label$6;
											case 7:
												goto label$5;
											case 8:
												goto label$4;
											case 9:
												goto label$3;
											case 10:
												goto label$2;
											default:
												goto label$11;
										}
*((void*)(local2) = local1 = 									*(void*)(local2) + 4*((void*)(local0) = 									*(void*)(local1)									return;
*((void*)(local2) = local1 = 								*(void*)(local2) + 4*((void*)(local0) = 								*(void*)(local1)								return;
*((void*)(local2) = local1 = 							*(void*)(local2) + 4*((void*)(local0) = 							*(void*)(local1)							return;
*((void*)(local2) = local1 = 						*(void*)(local2) + 7 & -8 + 8*((void*)(local0) = 						*(void*)(local1)						return;
*((void*)(local2) = local1 = 					*(void*)(local2) + 4*((void*)(local0) = 					*(void*)(local1)					return;
*((void*)(local2) = local1 = 				*(void*)(local2) + 4*((void*)(local0) = 				*(void*)(local1)				return;
*((void*)(local2) = local1 = 			*(void*)(local2) + 4*((void*)(local0) = 			*(void*)(local1)			return;
*((void*)(local2) = local1 = 		*(void*)(local2) + 4*((void*)(local0) = 		*(void*)(local1)		return;
*((void*)(local2) = local1 = 	*(void*)(local2) + 7 & -8 + 8*((void*)(local0) = 	*(void*)(local1)	return;
// Indirect call:
(local3)(local0, local2); 
}
void f27(int local0, int local1, int local2, int local3, int local4) {
	// Parsed WASM function locals:
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	label$1:
	if (local7 = local5 = global$0 - 256 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local7;
	label$3:
	if (local2 <= local3) break;	if (local4 & 73728) break;	/* Drop routine */
	f50(local5, local1, (	local6 = local4 < 256;
) ? (	local4 = local2 - local3;
) : (256);
);
	/* End of drop routine */
		label$4:
		if (local6) break;		local2 = local2 - local3;
		while (1) { // Loop name: 'label$5'
		f24(local0, local5, 256);
		if (		local4 = local4 + -256;
 > 255) break;
	} // End of loop 'label$5'
	local4 = local2 & 255;
	f24(local0, local5, local4);
	label$6:
	if (local8 = local5 + 256 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local8;
}
int f28(long local0, int local1) {
	label$1:
	if (local0 == 0) break;	while (1) { // Loop name: 'label$2'
*((void*)(local1 = local1 + -1) = (int)local0 & 7 | 48	if (local0 = local0 >> 3 != 0) break;
	} // End of loop 'label$2'
local1}
int f29(long local0, int local1, int local2) {
	label$1:
	if (local0 == 0) break;	while (1) { // Loop name: 'label$2'
*((void*)(local1 = local1 + -1) = 	*(void*)((int)local0 & 15 + 1712) | local2	if (local0 = local0 >> 4 != 0) break;
	} // End of loop 'label$2'
local1}
int f30(long local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	int local3; 
	int local4; 
	long local5; 
	label$1:
		label$2:
		if (local0 >= 4294967296) break;local5 = local0		break;	while (1) { // Loop name: 'label$3'
*((void*)(local1 = local1 + -1) = (int)local0 - local5 = local0 / 10 * 10 | 48local2 = local0 > 42949672959local0 = local5	if (local2) break;
	} // End of loop 'label$3'
	label$4:
	if (local2 = (int)local5 == 0) break;	while (1) { // Loop name: 'label$5'
*((void*)(local1 = local1 + -1) = local2 - local3 = local2 / 10 * 10 | 48local4 = local2 > 9local2 = local3	if (local4) break;
	} // End of loop 'label$5'
local1}
int f31(int local0, int local1, int local2) {
	f22(local0, local1, local2, 1, 2);
}
int f32(int local0, double local1, int local2, int local3, int local4, int local5) {
	// Parsed WASM function locals:
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	int local11; 
	int local12; 
	int local13; 
	int local14; 
	int local15; 
	int local16; 
	int local17; 
	int local18; 
	int local19; 
	int local20; 
	int local21; 
	int local22; 
	int local23; 
	long local24; 
	long local25; 
	double local26; 
	label$1:
	if (local22 = local6 = global$0 - 560 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local22;
*((void*)(local6) = 0; 
	label$3:
		label$4:
		if (		local24 = 		f34(local1);
;
 > -1) break;		local24 = 		f34(		local1 = -(local1);
);
;
		local7 = 1;
		local8 = 1728;
		break;		label$5:
		if (local4 & 2048 == 0) break;		local7 = 1;
		local8 = 1731;
		break;	local8 = (	local7 = local4 & 1;
) ? (1734) : (1729);
;
	label$6:
		label$7:
		if (local24 & 9218868437227405312 != 9218868437227405312) break;		f27(local0, 32, local2, 		local9 = local7 + 3;
, local4 & -65537);
		f24(local0, local8, local7);
		f24(local0, (local1 != local1) ? ((		local10 = local5 >> 5 & 1;
) ? (1755) : (1759);
) : ((local10) ? (1747) : (1751);
);
, 3);
		f27(local0, 32, local2, local9, local4 ^ 8192);
		break;		label$8:
		if (		local1 = 		local1 = 		f19(local1, local6 + 44);
;
 + local1;
 == 0.000000) break;		*((void*)(local6) = 		*(void*)(local6) + -1; 
	local11 = local6 + 16;
		label$9:
		if (		local12 = local5 | 32;
 != 97) break;		local14 = (		local13 = local5 & 32;
) ? (local8 + 9) : (local8);
;
			label$10:
			if (local3 > 11) break;			if (			local10 = 12 - local3;
 == 0) break;			local26 = 8.000000;
			while (1) { // Loop name: 'label$11'
			local26 = local26 * 16.000000;
			if (			local10 = local10 + -1;
) break;
		} // End of loop 'label$11'
			label$12:
			if (			*(void*)(local14) != 45) break;			local1 = -(local26 + -(local1) - local26);
			break;		local1 = local1 + local26 - local26;
		label$13:
		if (		local10 = 		f30((long)		local10 = 		*(void*)(local6);
 + 		local10 = local10 >> 31;
 ^ local10, local11);
;
 != local11) break;*((void*)(local6) = 48; 
		local10 = local6 + 15;
	local15 = local7 | 2;
	local16 = 	*(void*)(local6);
	*((void*)(	local17 = local10 + -2;
) = local5 + 15; 
	*((void*)(local10 + -1) = (local16 < 0) ? (45) : (43);
; 
	local18 = local4 & 8;
	local16 = local6 + 16;
	while (1) { // Loop name: 'label$14'
	local10 = local16;
		label$15:
			label$16:
			if (abs(local1) < 2147483648.000000 == 0) break;			local16 = (int)local1;
			break;		local16 = -2147483648;
	*((void*)(local10) = 	*(void*)(local16 + 1712) | local13; 
	local1 = local1 - (double)local16 * 16.000000;
		label$17:
		if (		local16 = local10 + 1;
 - local6 + 16 != 1) break;			label$18:
			if (local18) break;			if (local3 > 0) break;			if (local1 == 0.000000) break;*((void*)(local10) = 46; 
		local16 = local10 + 2;
	if (local1 != 0.000000) break;
	} // End of loop 'label$14'
	label$19:
		label$20:
		if (local3 == 0) break;		if (local16 - local6 + 16 + -2 >= local3) break;		local10 = local3 + local11 - local17 + 2;
		break;	local10 = local11 - local6 + 16 - local17 + local16;
	f27(local0, 32, local2, 	local9 = local10 + local15;
, local4);
	f24(local0, local14, local15);
	f27(local0, 48, local2, local9, local4 ^ 65536);
	f24(local0, local6 + 16, 	local16 = local16 - local6 + 16;
);
	f27(local0, 48, local10 - local16 + 	local13 = local11 - local17;
, 0, 0);
	f24(local0, local17, local13);
	f27(local0, 32, local2, local9, local4 ^ 8192);
	break;	local10 = local3 < 0;
	label$21:
	label$22:
	if (local1 != 0.000000) break;	local18 = 	*(void*)(local6);
	break;	*((void*)(local6) = 	local18 = 	*(void*)(local6) + -28;
	local1 = local1 * 268435456.000000;
	local14 = (local10) ? (6) : (local3);
;
	local13 = 	local19 = (local18 < 0) ? (local6 + 48) : (local6 + 336);
;
	while (1) { // Loop name: 'label$23'
	label$24:
	label$25:
	if (local1 < 4294967296.000000 & local1 >= 0.000000 == 0) break;	local10 = (int)local1;
	break;	local10 = 0;
*((void*)(local13) = local10; 
	local13 = local13 + 4;
	if (	local1 = local1 - (double)local10 * 1000000000.000000;
 != 0.000000) break;
	} // End of loop 'label$23'
	label$26:
	label$27:
	if (local18 >= 1) break;	local10 = local13;
	local16 = local19;
	break;	local16 = local19;
	while (1) { // Loop name: 'label$28'
	local18 = (local18 < 29) ? (local18) : (29);
;
	label$29:
	if (	local10 = local13 + -4;
 < local16) break;	local25 = (long)local18;
	local24 = 0;
	while (1) { // Loop name: 'label$30'
	*((void*)(local10) = 	local24 = 	*(void*)(local10) << local25 + local24 & 4294967295;
 - 	local24 = local24 / 1000000000;
 * 1000000000; 
	if (	local10 = local10 + -4;
 >= local16) break;
	} // End of loop 'label$30'
	if (	local10 = (int)local24;
 == 0) break;*((void*)(	local16 = local16 + -4;
) = local10; 
	label$31:
	while (1) { // Loop name: 'label$32'
	if (	local10 = local13;
 <= local16) break;	if (	*(void*)(	local13 = local10 + -4;
) == 0) break;
	} // End of loop 'label$32'
	*((void*)(local6) = 	local18 = 	*(void*)(local6) - local18;
	local13 = local10;
	if (local18 > 0) break;
	} // End of loop 'label$28'
	label$33:
	if (local18 > -1) break;	local20 = local14 + 25 / 9 + 1;
	local21 = local12 == 102;
	while (1) { // Loop name: 'label$34'
	local9 = (local18 < -9) ? (9) : (0 - local18);
;
	label$35:
	label$36:
	if (local16 < local10) break;	local16 = (	*(void*)(local16)) ? (local16) : (local16 + 4);
;
	break;	local17 = 1000000000 >> local9;
	local15 = -1 << local9 ^ -1;
	local18 = 0;
	local13 = local16;
	while (1) { // Loop name: 'label$37'
	*((void*)(local13) = 	local3 = 	*(void*)(local13);
 >> local9 + local18; 
	local18 = local3 & local15 * local17;
	if (	local13 = local13 + 4;
 < local10) break;
	} // End of loop 'label$37'
	local16 = (	*(void*)(local16)) ? (local16) : (local16 + 4);
;
	if (local18 == 0) break;*((void*)(local10) = local18; 
	local10 = local10 + 4;
	*((void*)(local6) = 	local18 = 	*(void*)(local6) + local9;
	local10 = (local10 - local13 >> 2 > local20) ? (	local13 = (local21) ? (local19) : (local16);
;
 + local20 << 2) : (local10);
;
	if (local18 < 0) break;
	} // End of loop 'label$34'
	local13 = 0;
	label$38:
	if (local16 >= local10) break;	local13 = local19 - local16 >> 2 * 9;
	local18 = 10;
	if (	local3 = 	*(void*)(local16);
 < 10) break;	while (1) { // Loop name: 'label$39'
	local13 = local13 + 1;
	if (local3 >= 	local18 = local18 * 10;
) break;
	} // End of loop 'label$39'
	label$40:
	if (	local18 = local14 - (local12 == 102) ? (0) : (local13);
 - local14 != 0 & local12 == 103;
 >= local10 - local19 >> 2 * 9 + -9) break;	local17 = 	local9 = 	local18 = local18 + 9216;
 / 9;
 << 2 + local19 + -4092;
	local3 = 10;
	label$41:
	if (	local18 = local18 - local9 * 9;
 > 7) break;	while (1) { // Loop name: 'label$42'
	local3 = local3 * 10;
	local9 = local18 < 7;
	local18 = local18 + 1;
	if (local9) break;
	} // End of loop 'label$42'
	local18 = 	local9 = 	*(void*)(local17);
 - 	local15 = local9 / local3;
 * local3;
	label$43:
	label$44:
	if (	local20 = local17 + 4;
 != local10) break;	if (local18 == 0) break;	local26 = (local18 < local21) ? (0.500000) : ((local20 == local10) ? ((local18 == 	local21 = local3 >> 1;
) ? (1.000000) : (1.500000);
) : (1.500000);
);
;
	local1 = (local15 & 1) ? (9007199254740994.000000) : (9007199254740992.000000);
;
	label$45:
	if (local7 == 0) break;	if (	*(void*)(local8) != 45) break;	local26 = -(local26);
	local1 = -(local1);
	*((void*)(local17) = 	local18 = local9 - local18;
	if (local1 + local26 == local1) break;	*((void*)(local17) = 	local13 = local18 + local3;
	label$46:
	if (local13 < 1000000000) break;	while (1) { // Loop name: 'label$47'
*((void*)(local17) = 0; 
	label$48:
	if (	local17 = local17 + -4;
 >= local16) break;*((void*)(	local16 = local16 + -4;
) = 0; 
	*((void*)(local17) = 	local13 = 	*(void*)(local17) + 1;
	if (local13 > 999999999) break;
	} // End of loop 'label$47'
	local13 = local19 - local16 >> 2 * 9;
	local18 = 10;
	if (	local3 = 	*(void*)(local16);
 < 10) break;	while (1) { // Loop name: 'label$49'
	local13 = local13 + 1;
	if (local3 >= 	local18 = local18 * 10;
) break;
	} // End of loop 'label$49'
	local10 = (local10 > local18) ? (	local18 = local17 + 4;
) : (local10);
;
	label$50:
	while (1) { // Loop name: 'label$51'
	label$52:
	if (	local18 = local10;
 > local16) break;	local21 = 0;
	break;	if (	*(void*)(	local10 = local18 + -4;
) == 0) break;
	} // End of loop 'label$51'
	local21 = 1;
	label$53:
	label$54:
	if (local12 == 103) break;	local15 = local4 & 8;
	break;	local14 = (	local3 = 	local10 = (local14) ? (local14) : (1);
;
 > local13 & local13 > -5;
) ? (local13 ^ -1) : (-1);
 + local10;
	local5 = (local3) ? (-1) : (-2);
 + local5;
	if (	local15 = local4 & 8;
) break;	local10 = 9;
	label$55:
	if (local21 == 0) break;	local10 = 9;
	if (	local9 = 	*(void*)(local18 + -4);
 == 0) break;	local3 = 10;
	local10 = 0;
	if (local9 % 10) break;	while (1) { // Loop name: 'label$56'
	local10 = local10 + 1;
	if (local9 % 	local3 = local3 * 10;
 == 0) break;
	} // End of loop 'label$56'
	local3 = local18 - local19 >> 2 * 9 + -9;
	label$57:
	if (local5 | 32 != 102) break;	local15 = 0;
	local14 = (local14 < local10) ? (local14) : (	local10 = (local10 > 0) ? (	local10 = local3 - local10;
) : (0);
;
);
;
	break;	local15 = 0;
	local14 = (local14 < local10) ? (local14) : (	local10 = (local10 > 0) ? (	local10 = local3 + local13 - local10;
) : (0);
;
);
;
	local3 = 	local12 = local14 | local15;
 != 0;
	label$58:
	label$59:
	if (	local17 = local5 | 32;
 != 102) break;	local10 = (local13 > 0) ? (local13) : (0);
;
	break;	label$60:
	if (local11 - 	local10 = 	f30((long)local13 + 	local10 = local13 >> 31;
 ^ local10, local11);
;
 > 1) break;	while (1) { // Loop name: 'label$61'
*((void*)(	local10 = local10 + -1;
) = 48; 
	if (local11 - local10 < 2) break;
	} // End of loop 'label$61'
*((void*)(	local20 = local10 + -2;
) = local5; 
	*((void*)(local10 + -1) = (local13 < 0) ? (45) : (43);
; 
	local10 = local11 - local20;
	f27(local0, 32, local2, 	local9 = local7 + local14 + local3 + local10 + 1;
, local4);
	f24(local0, local8, local7);
	f27(local0, 48, local2, local9, local4 ^ 65536);
	label$62:
	label$63:
	label$64:
	label$65:
	if (local17 != 102) break;	local17 = local6 + 16 | 8;
	local13 = local6 + 16 | 9;
	local16 = 	local3 = (local16 > local19) ? (local19) : (local16);
;
	while (1) { // Loop name: 'label$66'
	local10 = 	f30(	*(void*)(local16), local13);
;
	label$67:
	label$68:
	if (local16 == local3) break;	if (local10 <= local6 + 16) break;	while (1) { // Loop name: 'label$69'
*((void*)(	local10 = local10 + -1;
) = 48; 
	if (local10 > local6 + 16) break;	break;
	} // End of loop 'label$69'
	if (local10 != local13) break;*((void*)(local6) = 48; 
	local10 = local17;
	f24(local0, local10, local13 - local10);
	if (	local16 = local16 + 4;
 <= local19) break;
	} // End of loop 'label$66'
	label$70:
	if (local12 == 0) break;	f24(local0, 1763, 1);
	if (local16 >= local18) break;	if (local14 < 1) break;	while (1) { // Loop name: 'label$71'
	label$72:
	if (	local10 = 	f30(	*(void*)(local16), local13);
;
 <= local6 + 16) break;	while (1) { // Loop name: 'label$73'
*((void*)(	local10 = local10 + -1;
) = 48; 
	if (local10 > local6 + 16) break;
	} // End of loop 'label$73'
	f24(local0, local10, (local14 < 9) ? (local14) : (9);
);
	local10 = local14 + -9;
	if (	local16 = local16 + 4;
 >= local18) break;	local3 = local14 > 9;
	local14 = local10;
	if (local3) break;	break;
	} // End of loop 'label$71'
	label$74:
	if (local14 < 0) break;	local17 = (local21) ? (local18) : (local16 + 4);
;
	local19 = local6 + 16 | 8;
	local18 = local6 + 16 | 9;
	local13 = local16;
	while (1) { // Loop name: 'label$75'
	label$76:
	if (	local10 = 	f30(	*(void*)(local13), local18);
;
 != local18) break;*((void*)(local6) = 48; 
	local10 = local19;
	label$77:
	label$78:
	if (local13 == local16) break;	if (local10 <= local6 + 16) break;	while (1) { // Loop name: 'label$79'
*((void*)(	local10 = local10 + -1;
) = 48; 
	if (local10 > local6 + 16) break;	break;
	} // End of loop 'label$79'
	f24(local0, local10, 1);
	local10 = local10 + 1;
	label$80:
	if (local15) break;	if (local14 < 1) break;	f24(local0, 1763, 1);
	f24(local0, local10, (local14 > local3) ? (	local3 = local18 - local10;
) : (local14);
);
	local14 = local14 - local3;
	if (	local13 = local13 + 4;
 >= local17) break;	if (local14 > -1) break;
	} // End of loop 'label$75'
	f27(local0, 48, local14 + 18, 18, 0);
	f24(local0, local20, local11 - local20);
	break;	local10 = local14;
	f27(local0, 48, local10 + 9, 9, 0);
	f27(local0, 32, local2, local9, local4 ^ 8192);
	label$81:
	if (local23 = local6 + 560 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local23;
(local9 < local2) ? (local2) : (local9);
}
void f33(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
*((void*)(local1) = local2 = 	*(void*)(local1) + 15 & -16 + 16*((void*)(local0) = 	f48(	*(void*)(local2), 	*(void*)(local2));
}
long f34(double local0) {
(long)local0}
int f35() {
	ffimport$0(2340);
2348}
void f36() {
	ffimport$1(2340);
}
int f37(int local0) {
	// Parsed WASM function locals:
	int local1; 
*((void*)(local0) = local1 = 	*(void*)(local0) + -1 | local1	label$1:
	if (local1 = 	*(void*)(local0) & 8 == 0) break;*((void*)(local0) = local1 | 32	return -1;
*((void*)(local0) = 0*((void*)(local0) = local1 = 	*(void*)(local0)*((void*)(local0) = local1*((void*)(local0) = local1 + 	*(void*)(local0)0}
int f38(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	local1 = 0;
	label$1:
	if (	*(void*)(local2 = 	*(void*)(0)) < 0) break;local1 = 	f10(local2);
	label$2:
		label$3:
		if (		f40(local0, local2);
 >= 0) break;local0 = -1		break;		label$4:
		if (		*(void*)(local2) == 10) break;		if (local0 = 		*(void*)(local2) >= 		*(void*)(local2)) break;*((void*)(local2) = local0 + 1*((void*)(local0) = 10local0 = 0		break;local0 = 	f44(local2, 10);
 >> 31	label$5:
	if (local1 == 0) break;	f11(local2);
local0}
int f39(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	int local3; 
	local1 = local0;
	label$1:
		label$2:
		if (local0 & 3 == 0) break;			label$3:
			if (			*(void*)(local0)) break;local1 = local0			break;local1 = local0		while (1) { // Loop name: 'label$4'
		if (local1 = local1 + 1 & 3 == 0) break;		if (		*(void*)(local1) == 0) break;		break;
	} // End of loop 'label$4'
	while (1) { // Loop name: 'label$5'
local1 = local2 = local1 + 4	if (local3 = 	*(void*)(local2) ^ -1 & local3 + -16843009 & -2139062144 == 0) break;
	} // End of loop 'label$5'
	label$6:
	if (local3 & 255) break;local1 = local2	break;	while (1) { // Loop name: 'label$7'
local3 = 	*(void*)(local2)local2 = local1 = local2 + 1	if (local3) break;
	} // End of loop 'label$7'
local1 - local0}
int f40(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
(local2 = 	f39(local0);
 != 	f21(local0, 1, local2, local1);
) ? (-1) : (0);
}
int f41(int local0) {
0}
long f42(int local0, long local1, int local2) {
0}
int f43(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	label$1:
	if (local9 = local3 = global$0 - 32 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local9;
	*((void*)(local3) = 	local4 = 	*(void*)(local0);
	local5 = 	*(void*)(local0);
*((void*)(local3) = local2; 
*((void*)(local3) = local1; 
	*((void*)(local3) = 	local1 = local5 - local4;
	local6 = local1 + local2;
	local5 = 2;
	local1 = local3 + 16;
	while (1) { // Loop name: 'label$3'
	label$4:
		label$5:
		if (		f45(		ffimport$2(		*(void*)(local0), local1, local5, local3 + 12);
);
 == 0) break;		local4 = -1;
*((void*)(local3) = -1; 
		break;	local4 = 	*(void*)(local3);
	label$6:
		label$7:
			label$8:
			if (local6 != local4) break;			*((void*)(local0) = 			local1 = 			*(void*)(local0);
*((void*)(local0) = local1; 
			*((void*)(local0) = local1 + 			*(void*)(local0); 
			local4 = local2;
			break;		if (local4 > -1) break;		local4 = 0;
*((void*)(local0) = 0; 
*((void*)(local0) = 0; 
		*((void*)(local0) = 		*(void*)(local0) | 32; 
		if (local5 == 2) break;		local4 = local2 - 		*(void*)(local1);
		label$9:
		if (local10 = local3 + 32 < global$2) {
		ffimport$5();

		} // <No else block>
		global$0 = local10;
	return local4;
	*((void*)(	local1 = (	local8 = local4 > 	local7 = 	*(void*)(local1);
;
) ? (local1 + 8) : (local1);
;
) = 	*(void*)(local1) + 	local7 = local4 - (local8) ? (local7) : (0);
;
; 
	*((void*)(local1) = 	*(void*)(local1) - local7; 
	local6 = local6 - local4;
	local5 = local5 - local8;
	break;
	} // End of loop 'label$3'
}
int f44(int local0, int local1) {
	// Parsed WASM function locals:
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	label$1:
	if (local5 = local2 = global$0 - 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local5;
*((void*)(local2) = local1; 
	label$3:
		label$4:
		if (		local3 = 		*(void*)(local0);
) break;		local3 = -1;
		if (		f37(local0);
) break;		local3 = 		*(void*)(local0);
		label$5:
		if (		local4 = 		*(void*)(local0);
 >= local3) break;		if (		local3 = local1 & 255;
 == 		*(void*)(local0)) break;		*((void*)(local0) = local4 + 1; 
*((void*)(local4) = local1; 
		break;	local3 = -1;
	if (// Indirect call:
(	*(void*)(local0))(local0, local2 + 15, 1); 
 != 1) break;	local3 = 	*(void*)(local2);
	label$6:
	if (local6 = local2 + 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local6;
local3}
int f45(int local0) {
	label$1:
	if (local0) break;	return 0;
*((void*)(	f12();
) = local0-1}
void f46(int local0, long local1, long local2, int local3) {
	// Parsed WASM function locals:
	long local4; 
	label$1:
		label$2:
			label$3:
			if (local3 & 64 == 0) break;local1 = local2 >> (long)local3 + -64local4 = 0local2 = 0			break;		if (local3 == 0) break;local1 = local2 << (long)64 - local3 | local1 >> local4 = (long)local3local2 = local2 >> local4local4 = 0local1 = local4 | local1*((void*)(local0) = local1*((void*)(local0) = local2}
void f47(int local0, long local1, long local2, int local3) {
	// Parsed WASM function locals:
	long local4; 
	label$1:
		label$2:
			label$3:
			if (local3 & 64 == 0) break;local2 = local1 << (long)local3 + -64local1 = 0			break;		if (local3 == 0) break;local2 = local1 >> (long)64 - local3 | local2 << local4 = (long)local3local1 = local1 << local4local2 = local2 | 0*((void*)(local0) = local1*((void*)(local0) = local2}
double f48(long local0, long local1) {
	// Parsed WASM function locals:
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	long local6; 
	long local7; 
	label$1:
	if (local4 = local2 = global$0 - 32 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local4;
	label$3:
		label$4:
		if (		local6 = local1 & 9223372036854775807;
 + -4323737117252386816 >= local6 + -4899634919602388992) break;		local6 = local0 >> 60 | local1 << 4;
			label$5:
			if (			local0 = local0 & 1152921504606846975;
 > 576460752303423489) break;			local7 = local6 + 4611686018427387905;
			break;		local7 = local6 + 4611686018427387904;
		if (local0 ^ 576460752303423488 != 0) break;		local7 = local7 & 1 + local7;
		break;		label$6:
		if ((local6 == 9223090561878065152) ? (local0 == 0) : (local6 > 9223090561878065152);
) break;		local7 = local0 >> 60 | local1 << 4 & 2251799813685247 | 9221120237041090560;
		break;	local7 = 9218868437227405312;
	if (local6 > 4899634919602388991) break;	local7 = 0;
	if (	local3 = (int)local6 >> 48;
 < 15249) break;	f46(local2, local0, 	local6 = local1 & 281474976710655 | 281474976710656;
, 15361 - local3);
	f47(local2 + 16, local0, local6, local3 + -15233);
	local7 = 	local6 = 	*(void*)(local2);
 >> 60 | 	*(void*)(local2 + 8) << 4;
		label$7:
		if (		local6 = local6 & 1152921504606846975 | (long)		*(void*)(local2) | 		*(void*)(local2 + 16 + 8) != 0;
 > 576460752303423489) break;		local7 = local7 + 1;
		break;	if (local6 ^ 576460752303423488 != 0) break;	local7 = local7 & 1 + local7;
	label$8:
	if (local5 = local2 + 32 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local5;
(double)local7 | local1 & -9223372036854775808}
int f49(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	int local4; 
	int local5; 
	label$1:
	if (local2 < 8192) break;	/* Drop routine */
	ffimport$3(local0, local1, local2);
	/* End of drop routine */
	return local0;
local3 = local0 + local2	label$2:
		label$3:
		if (local1 ^ local0 & 3) break;			label$4:
				label$5:
				if (local2 >= 1) break;local2 = local0				break;				label$6:
				if (local0 & 3) break;local2 = local0				break;local2 = local0			while (1) { // Loop name: 'label$7'
*((void*)(local2) = 			*(void*)(local1)local1 = local1 + 1			if (local2 = local2 + 1 >= local3) break;			if (local2 & 3) break;
		} // End of loop 'label$7'
		label$8:
		if (local4 = local3 & -4 < 64) break;		if (local2 > local5 = local4 + -64) break;		while (1) { // Loop name: 'label$9'
*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)*((void*)(local2) = 		*(void*)(local1)local1 = local1 + 64		if (local2 = local2 + 64 <= local5) break;
	} // End of loop 'label$9'
	if (local2 >= local4) break;	while (1) { // Loop name: 'label$10'
*((void*)(local2) = 	*(void*)(local1)local1 = local1 + 4	if (local2 = local2 + 4 < local4) break;	break;
	} // End of loop 'label$10'
	label$11:
	if (local3 >= 4) break;local2 = local0	break;	label$12:
	if (local4 = local3 + -4 >= local0) break;local2 = local0	break;local2 = local0	while (1) { // Loop name: 'label$13'
*((void*)(local2) = 	*(void*)(local1)*((void*)(local2) = 	*(void*)(local1)*((void*)(local2) = 	*(void*)(local1)*((void*)(local2) = 	*(void*)(local1)local1 = local1 + 4	if (local2 = local2 + 4 <= local4) break;
	} // End of loop 'label$13'
	label$14:
	if (local2 >= local3) break;	while (1) { // Loop name: 'label$15'
*((void*)(local2) = 	*(void*)(local1)local1 = local1 + 1	if (local2 = local2 + 1 != local3) break;
	} // End of loop 'label$15'
local0}
int f50(int local0, int local1, int local2) {
	// Parsed WASM function locals:
	int local3; 
	int local4; 
	int local5; 
	long local6; 
	label$1:
	if (local2 == 0) break;*((void*)(local3 = local2 + local0 + -1) = local1*((void*)(local0) = local1	if (local2 < 3) break;*((void*)(local3 + -2) = local1*((void*)(local0) = local1*((void*)(local3 + -3) = local1*((void*)(local0) = local1	if (local2 < 7) break;*((void*)(local3 + -4) = local1*((void*)(local0) = local1	if (local2 < 9) break;*((void*)(local3 = local0 + local4 = 0 - local0 & 3) = local1 = local1 & 255 * 16843009*((void*)(local2 = local3 + local4 = local2 - local4 & -4 + -4) = local1	if (local4 < 9) break;*((void*)(local3) = local1*((void*)(local3) = local1*((void*)(local2 + -8) = local1*((void*)(local2 + -12) = local1	if (local4 < 25) break;*((void*)(local3) = local1*((void*)(local3) = local1*((void*)(local3) = local1*((void*)(local3) = local1*((void*)(local2 + -16) = local1*((void*)(local2 + -20) = local1*((void*)(local2 + -24) = local1*((void*)(local2 + -28) = local1	if (local2 = local4 - local5 = local3 & 4 | 24 < 32) break;local6 = local6 = (long)local1 << 32 | local6local1 = local3 + local5	while (1) { // Loop name: 'label$2'
*((void*)(local1) = local6*((void*)(local1) = local6*((void*)(local1) = local6*((void*)(local1) = local6local1 = local1 + 32	if (local2 = local2 + -32 > 31) break;
	} // End of loop 'label$2'
local0}
int f51(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	label$1:
	if (local0 = local2 = 	*(void*)(local1 = 	f0();
) + local0 + 3 & -4 > -1) break;*((void*)(	f12();
) = 48	return -1;
	label$2:
	if (local0 <= /* Host call */
host_get_current_memory() << 16) break;	if (	ffimport$4(local0);
) break;*((void*)(	f12();
) = 48	return -1;
*((void*)(local1) = local0local2}
int f52(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	int local7; 
	int local8; 
	int local9; 
	int local10; 
	int local11; 
	int local12; 
	int local13; 
	label$1:
	if (local12 = local1 = global$0 - 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local12;
	label$3:
		label$4:
			label$5:
				label$6:
					label$7:
						label$8:
							label$9:
								label$10:
									label$11:
										label$12:
											label$13:
												label$14:
												if (local0 > 244) break;													label$15:
													if (													local0 = 													local2 = 													*(void*)(0);
 >> 													local4 = 													local3 = (local0 < 11) ? (16) : (local0 + 11 & -8);
;
 >> 3;
;
 & 3 == 0) break;													local0 = 													local4 = 													*(void*)(													local5 = 													local3 = local0 ^ -1 & 1 + local4;
 << 3;
 + 3432);
 + 8;
														label$16:
															label$17:
															if (															local6 = 															*(void*)(local4);
 != 															local5 = local5 + 3424;
) break;															*((void*)(0) = local2 & _rotl(-2, local3); 
															break;	/* Drop routine */
														*(void*)(0) > local6	/* End of drop routine */
*((void*)(local6) = local5; 
*((void*)(local5) = local6; 
													*((void*)(local4) = 													local6 = local3 << 3;
 | 3; 
													*((void*)(													local4 = local4 + local6;
) = 													*(void*)(local4) | 1; 
													break;												if (local3 <= 												local7 = 												*(void*)(0);
) break;													label$18:
													if (local0 == 0) break;														label$19:
															label$20:
															if (															local0 = 															*(void*)(															local4 = 															*(void*)(															local5 = 															local6 = 															local6 = 															local4 = 															local0 = 															local0 = local0 << local4 & 															local0 = 2 << local4;
 | 0 - local0;
 & 0 - local0 + -1;
 >> 															local0 = local0 >> 12 & 16;
;
 >> 5 & 8;
 | local0 | 															local4 = 															local0 = local4 >> local6;
 >> 2 & 4;
 | 															local4 = 															local0 = local0 >> local4;
 >> 1 & 2;
 | 															local4 = 															local0 = local0 >> local4;
 >> 1 & 1;
 + local0 >> local4;
 << 3;
 + 3432);
);
 != 															local5 = local5 + 3424;
) break;															*((void*)(0) = 															local2 = local2 & _rotl(-2, local6);
															break;	/* Drop routine */
														*(void*)(0) > local0	/* End of drop routine */
*((void*)(local0) = local5; 
*((void*)(local5) = local0; 
													local0 = local4 + 8;
													*((void*)(local4) = local3 | 3; 
													*((void*)(													local5 = local4 + local3;
) = 													local6 = 													local8 = local6 << 3;
 - local3;
 | 1; 
*((void*)(local4 + local8) = local6; 
														label$21:
														if (local7 == 0) break;														local3 = 														local8 = local7 >> 3;
 << 3 + 3424;
														local4 = 														*(void*)(0);
															label$22:
																label$23:
																if (local2 & 																local8 = 1 << local8;
) break;																*((void*)(0) = local2 | local8; 
																local8 = local3;
																break;															local8 = 															*(void*)(local3);
*((void*)(local3) = local4; 
*((void*)(local8) = local4; 
*((void*)(local4) = local3; 
*((void*)(local4) = local8; 
*((void*)(0) = local5; 
*((void*)(0) = local6; 
													break;												if (												local9 = 												*(void*)(0);
 == 0) break;												local4 = 												*(void*)(												local5 = 												*(void*)(												local6 = 												local4 = 												local0 = local9 & 0 - local9 + -1;
 >> 												local0 = local0 >> 12 & 16;
;
 >> 5 & 8;
 | local0 | 												local4 = 												local0 = local4 >> local6;
 >> 2 & 4;
 | 												local4 = 												local0 = local0 >> local4;
 >> 1 & 2;
 | 												local4 = 												local0 = local0 >> local4;
 >> 1 & 1;
 + local0 >> local4 << 2 + 3688);
) & -8 - local3;
												local6 = local5;
													label$24:
													while (1) { // Loop name: 'label$25'
														label$26:
														if (														local0 = 														*(void*)(local6);
) break;														if (														local0 = 														*(void*)(local6 + 20);
 == 0) break;													local4 = (													local6 = local6 < local4;
) ? (													local6 = 													*(void*)(local0) & -8 - local3;
) : (local4);
;
													local5 = (local6) ? (local0) : (local5);
;
													local6 = local0;
													break;
												} // End of loop 'label$25'
											local10 = 											*(void*)(local5);
												label$27:
												if (												local8 = 												*(void*)(local5);
 == local5) break;													label$28:
													if (													*(void*)(0) > 													local0 = 													*(void*)(local5);
) break;	/* Drop routine */
													*(void*)(local0) != local5	/* End of drop routine */
*((void*)(local0) = local8; 
*((void*)(local8) = local0; 
												break;												label$29:
												if (												local0 = 												*(void*)(												local6 = local5 + 20;
);
) break;												if (												local0 = 												*(void*)(local5);
 == 0) break;												local6 = local5 + 16;
											while (1) { // Loop name: 'label$30'
											local11 = local6;
											if (											local0 = 											*(void*)(											local6 = 											local8 = local0;
 + 20;
);
) break;											local6 = local8 + 16;
											if (											local0 = 											*(void*)(local8);
) break;
										} // End of loop 'label$30'
*((void*)(local11) = 0; 
										break;									local3 = -1;
									if (local0 > -65) break;									local3 = 									local0 = local0 + 11;
 & -8;
									if (									local7 = 									*(void*)(0);
 == 0) break;									local11 = 0;
										label$31:
										if (										local0 = local0 >> 8;
 == 0) break;										local11 = 31;
										if (local3 > 16777215) break;										local11 = 										local0 = 										local6 = 										local0 = local0 << 										local4 = local0 + 1048320 >> 16 & 8;
;
 << 										local0 = local0 + 520192 >> 16 & 4;
;
 << 										local6 = local6 + 245760 >> 16 & 2;
 >> 15 - local0 | local4 | local6;
 << 1 | local3 >> local0 + 21 & 1 + 28;
									local6 = 0 - local3;
										label$32:
											label$33:
												label$34:
													label$35:
													if (													local4 = 													*(void*)(local11 << 2 + 3688);
) break;													local0 = 0;
													local8 = 0;
													break;												local5 = local3 << (local11 == 31) ? (0) : (25 - local11 >> 1);
;
												local0 = 0;
												local8 = 0;
												while (1) { // Loop name: 'label$36'
													label$37:
													if (													local2 = 													*(void*)(local4) & -8 - local3;
 >= local6) break;													local6 = local2;
													local8 = local4;
													if (local2) break;													local6 = 0;
													local8 = local4;
													local0 = local4;
													break;												local0 = (local2) ? ((local2 == 												local4 = 												*(void*)(local4 + local5 >> 29 & 4 + 16);
) ? (local0) : (												local2 = 												*(void*)(local4 + 20);
);
) : (local0);
;
												local5 = local5 << local4 != 0;
												if (local4) break;
											} // End of loop 'label$36'
											label$38:
											if (local0 | local8) break;											if (											local0 = 											local0 = 2 << local11;
 | 0 - local0 & local7;
 == 0) break;											local0 = 											*(void*)(											local5 = 											local4 = 											local0 = local0 & 0 - local0 + -1;
 >> 											local0 = local0 >> 12 & 16;
;
 >> 5 & 8;
 | local0 | 											local4 = 											local0 = local4 >> local5;
 >> 2 & 4;
 | 											local4 = 											local0 = local0 >> local4;
 >> 1 & 2;
 | 											local4 = 											local0 = local0 >> local4;
 >> 1 & 1;
 + local0 >> local4 << 2 + 3688);
										if (local0 == 0) break;									while (1) { // Loop name: 'label$39'
									local5 = 									local2 = 									*(void*)(local0) & -8 - local3;
 < local6;
										label$40:
										if (										local4 = 										*(void*)(local0);
) break;										local4 = 										*(void*)(local0 + 20);
									local6 = (local5) ? (local2) : (local6);
;
									local8 = (local5) ? (local0) : (local8);
;
									local0 = local4;
									if (local4) break;
								} // End of loop 'label$39'
							if (local8 == 0) break;							if (local6 >= 							*(void*)(0) - local3) break;							local11 = 							*(void*)(local8);
								label$41:
								if (								local5 = 								*(void*)(local8);
 == local8) break;									label$42:
									if (									*(void*)(0) > 									local0 = 									*(void*)(local8);
) break;	/* Drop routine */
									*(void*)(local0) != local8	/* End of drop routine */
*((void*)(local0) = local5; 
*((void*)(local5) = local0; 
								break;								label$43:
								if (								local0 = 								*(void*)(								local4 = local8 + 20;
);
) break;								if (								local0 = 								*(void*)(local8);
 == 0) break;								local4 = local8 + 16;
							while (1) { // Loop name: 'label$44'
							local2 = local4;
							if (							local0 = 							*(void*)(							local4 = 							local5 = local0;
 + 20;
);
) break;							local4 = local5 + 16;
							if (							local0 = 							*(void*)(local5);
) break;
						} // End of loop 'label$44'
*((void*)(local2) = 0; 
						break;						label$45:
						if (						local0 = 						*(void*)(0);
 < local3) break;						local4 = 						*(void*)(0);
							label$46:
								label$47:
								if (								local6 = local0 - local3;
 < 16) break;*((void*)(0) = local6; 
								*((void*)(0) = 								local5 = local4 + local3;
								*((void*)(local5) = local6 | 1; 
*((void*)(local4 + local0) = local6; 
								*((void*)(local4) = local3 | 3; 
								break;*((void*)(0) = 0; 
*((void*)(0) = 0; 
							*((void*)(local4) = local0 | 3; 
							*((void*)(							local0 = local4 + local0;
) = 							*(void*)(local0) | 1; 
						local0 = local4 + 8;
						break;						label$48:
						if (						local5 = 						*(void*)(0);
 <= local3) break;						*((void*)(0) = 						local4 = local5 - local3;
						*((void*)(0) = 						local6 = 						local0 = 						*(void*)(0);
 + local3;
						*((void*)(local6) = local4 | 1; 
						*((void*)(local0) = local3 | 3; 
						local0 = local0 + 8;
						break;						label$49:
							label$50:
							if (							*(void*)(0) == 0) break;							local4 = 							*(void*)(0);
							break;*((void*)(0) = -1; 
*((void*)(0) = 17592186048512; 
						*((void*)(0) = local1 + 12 & -16 ^ 1431655768; 
*((void*)(0) = 0; 
*((void*)(0) = 0; 
						local4 = 4096;
					local0 = 0;
					if (					local8 = 					local2 = local4 + 					local7 = local3 + 47;
;
 & 					local11 = 0 - local4;
;
 <= local3) break;					local0 = 0;
						label$51:
						if (						local4 = 						*(void*)(0);
 == 0) break;						if (						local9 = 						local6 = 						*(void*)(0);
 + local8;
 <= local6) break;						if (local9 > local4) break;					if (					*(void*)(0) & 4) break;						label$52:
							label$53:
								label$54:
								if (								local4 = 								*(void*)(0);
 == 0) break;								local0 = 3832;
								while (1) { // Loop name: 'label$55'
									label$56:
									if (									local6 = 									*(void*)(local0);
 > local4) break;									if (local6 + 									*(void*)(local0) > local4) break;								if (								local0 = 								*(void*)(local0);
) break;
							} // End of loop 'label$55'
						if (						local5 = 						f51(0);
;
 == -1) break;						local2 = local8;
							label$57:
							if (							local4 = 							local0 = 							*(void*)(0);
 + -1;
 & local5 == 0) break;							local2 = local8 - local5 + local4 + local5 & 0 - local0;
						if (local2 <= local3) break;						if (local2 > 2147483646) break;							label$58:
							if (							local0 = 							*(void*)(0);
 == 0) break;							if (							local6 = 							local4 = 							*(void*)(0);
 + local2;
 <= local4) break;							if (local6 > local0) break;						if (						local0 = 						f51(local2);
;
 != local5) break;						break;					if (					local2 = local2 - local5 & local11;
 > 2147483646) break;					if (					local5 = 					f51(local2);
;
 == 					*(void*)(local0) + 					*(void*)(local0)) break;					local0 = local5;
				local5 = local0;
					label$59:
					if (local3 + 48 <= local2) break;					if (local2 > 2147483646) break;					if (local5 == -1) break;					if (					local0 = local7 - local2 + 					local0 = 					*(void*)(0);
 & 0 - local0;
 > 2147483646) break;						label$60:
						if (						f51(local0);
 == -1) break;						local2 = local0 + local2;
						break;	/* Drop routine */
					f51(0 - local2);
	/* End of drop routine */
					break;				if (local5 != -1) break;				break;			local8 = 0;
			break;		local5 = 0;
		break;	if (local5 != -1) break;	*((void*)(0) = 	*(void*)(0) | 4; 
	if (local8 > 2147483646) break;	if (	local5 = 	f51(local8);
;
 >= 	local0 = 	f51(0);
;
) break;	if (local5 == -1) break;	if (local0 == -1) break;	if (	local2 = local0 - local5;
 <= local3 + 40) break;	*((void*)(0) = 	local0 = 	*(void*)(0) + local2;
	label$61:
	if (local0 <= 	*(void*)(0)) break;*((void*)(0) = local0; 
	label$62:
	label$63:
	label$64:
		label$65:
		if (		local4 = 		*(void*)(0);
 == 0) break;		local0 = 3832;
		while (1) { // Loop name: 'label$66'
		if (local5 == 		local6 = 		*(void*)(local0);
 + 		local8 = 		*(void*)(local0);
) break;		if (		local0 = 		*(void*)(local0);
) break;		break;
	} // End of loop 'label$66'
	label$67:
		label$68:
		if (		local0 = 		*(void*)(0);
 == 0) break;		if (local5 >= local0) break;*((void*)(0) = local5; 
	local0 = 0;
*((void*)(0) = local2; 
*((void*)(0) = local5; 
*((void*)(0) = -1; 
	*((void*)(0) = 	*(void*)(0); 
*((void*)(0) = 0; 
	while (1) { // Loop name: 'label$69'
	*((void*)(	local4 = local0 << 3;
 + 3432) = 	local6 = local4 + 3424;
*((void*)(local4 + 3436) = local6; 
	if (	local0 = local0 + 1;
 != 32) break;
	} // End of loop 'label$69'
	*((void*)(0) = 	local6 = 	local0 = local2 + -40;
 - 	local4 = (local5 + 8 & 7) ? (-8 - local5 & 7) : (0);
;
;
	*((void*)(0) = 	local4 = local5 + local4;
	*((void*)(local4) = local6 | 1; 
*((void*)(local5 + local0) = 40; 
	*((void*)(0) = 	*(void*)(0); 
	break;	if (	*(void*)(local0) & 8) break;	if (local5 <= local4) break;	if (local6 > local4) break;	*((void*)(local0) = local8 + local2; 
	*((void*)(0) = 	local6 = local4 + 	local0 = (local4 + 8 & 7) ? (-8 - local4 & 7) : (0);
;
;
	*((void*)(0) = 	local0 = 	local5 = 	*(void*)(0) + local2;
 - local0;
	*((void*)(local6) = local0 | 1; 
*((void*)(local4 + local5) = 40; 
	*((void*)(0) = 	*(void*)(0); 
	break;	label$70:
	if (local5 >= 	local8 = 	*(void*)(0);
) break;*((void*)(0) = local5; 
	local8 = local5;
	local6 = local5 + local2;
	local0 = 3832;
	label$71:
	label$72:
	label$73:
	label$74:
		label$75:
			label$76:
				label$77:
				while (1) { // Loop name: 'label$78'
				if (				*(void*)(local0) == local6) break;				if (				local0 = 				*(void*)(local0);
) break;				break;
			} // End of loop 'label$78'
		if (		*(void*)(local0) & 8 == 0) break;	local0 = 3832;
	while (1) { // Loop name: 'label$79'
		label$80:
		if (		local6 = 		*(void*)(local0);
 > local4) break;		if (		local6 = local6 + 		*(void*)(local0);
 > local4) break;	local0 = 	*(void*)(local0);
	break;
	} // End of loop 'label$79'
*((void*)(local0) = local5; 
	*((void*)(local0) = 	*(void*)(local0) + local2; 
	*((void*)(	local11 = local5 + (local5 + 8 & 7) ? (-8 - local5 & 7) : (0);
;
) = local3 | 3; 
	local0 = 	local5 = local6 + (local6 + 8 & 7) ? (-8 - local6 & 7) : (0);
;
 - local11 - local3;
	local6 = local11 + local3;
	label$81:
	if (local4 != local5) break;*((void*)(0) = local6; 
	*((void*)(0) = 	local0 = 	*(void*)(0) + local0;
	*((void*)(local6) = local0 | 1; 
	break;	label$82:
	if (	*(void*)(0) != local5) break;*((void*)(0) = local6; 
	*((void*)(0) = 	local0 = 	*(void*)(0) + local0;
	*((void*)(local6) = local0 | 1; 
*((void*)(local6 + local0) = local0; 
	break;	label$83:
	if (	local4 = 	*(void*)(local5);
 & 3 != 1) break;	local7 = local4 & -8;
	label$84:
		label$85:
		if (local4 > 255) break;		local3 = 		*(void*)(local5);
			label$86:
			if (			local2 = 			*(void*)(local5);
 == 			local4 = 			local9 = local4 >> 3;
 << 3 + 3424;
) break;	/* Drop routine */
local8 > local2	/* End of drop routine */
			label$87:
			if (local3 != local2) break;			*((void*)(0) = 			*(void*)(0) & _rotl(-2, local9); 
			break;			label$88:
			if (local3 == local4) break;	/* Drop routine */
local8 > local3	/* End of drop routine */
*((void*)(local2) = local3; 
*((void*)(local3) = local2; 
		break;	local9 = 	*(void*)(local5);
		label$89:
			label$90:
			if (			local2 = 			*(void*)(local5);
 == local5) break;				label$91:
				if (local8 > 				local4 = 				*(void*)(local5);
) break;	/* Drop routine */
				*(void*)(local4) != local5	/* End of drop routine */
*((void*)(local4) = local2; 
*((void*)(local2) = local4; 
			break;			label$92:
			if (			local3 = 			*(void*)(			local4 = local5 + 20;
);
) break;			if (			local3 = 			*(void*)(			local4 = local5 + 16;
);
) break;			local2 = 0;
			break;		while (1) { // Loop name: 'label$93'
		local8 = local4;
		if (		local3 = 		*(void*)(		local4 = 		local2 = local3;
 + 20;
);
) break;		local4 = local2 + 16;
		if (		local3 = 		*(void*)(local2);
) break;
	} // End of loop 'label$93'
*((void*)(local8) = 0; 
	if (local9 == 0) break;	label$94:
		label$95:
		if (		*(void*)(		local4 = 		local3 = 		*(void*)(local5);
 << 2 + 3688;
) != local5) break;*((void*)(local4) = local2; 
		if (local2) break;		*((void*)(0) = 		*(void*)(0) & _rotl(-2, local3); 
		break;*((void*)(local9 + (	*(void*)(local9) == local5) ? (16) : (20);
) = local2; 
	if (local2 == 0) break;*((void*)(local2) = local9; 
	label$96:
	if (	local4 = 	*(void*)(local5);
 == 0) break;*((void*)(local2) = local4; 
*((void*)(local4) = local2; 
	if (	local4 = 	*(void*)(local5);
 == 0) break;*((void*)(local2 + 20) = local4; 
*((void*)(local4) = local2; 
	local0 = local7 + local0;
	local5 = local5 + local7;
	*((void*)(local5) = 	*(void*)(local5) & -2; 
	*((void*)(local6) = local0 | 1; 
*((void*)(local6 + local0) = local0; 
	label$97:
	if (local0 > 255) break;	local0 = 	local4 = local0 >> 3;
 << 3 + 3424;
	label$98:
	label$99:
	if (	local3 = 	*(void*)(0);
 & 	local4 = 1 << local4;
) break;	*((void*)(0) = local3 | local4; 
	local4 = local0;
	break;	local4 = 	*(void*)(local0);
*((void*)(local0) = local6; 
*((void*)(local4) = local6; 
*((void*)(local6) = local0; 
*((void*)(local6) = local4; 
	break;	local4 = 0;
	label$100:
	if (	local3 = local0 >> 8;
 == 0) break;	local4 = 31;
	if (local0 > 16777215) break;	local4 = 	local4 = 	local5 = 	local3 = local3 << 	local4 = local3 + 1048320 >> 16 & 8;
;
 << 	local3 = local3 + 520192 >> 16 & 4;
;
 << 	local5 = local5 + 245760 >> 16 & 2;
 >> 15 - local3 | local4 | local5;
 << 1 | local0 >> local4 + 21 & 1 + 28;
*((void*)(local6) = local4; 
*((void*)(local6) = 0; 
	local3 = local4 << 2 + 3688;
	label$101:
	label$102:
	if (	local5 = 	*(void*)(0);
 & 	local8 = 1 << local4;
) break;	*((void*)(0) = local5 | local8; 
*((void*)(local3) = local6; 
*((void*)(local6) = local3; 
	break;	local4 = local0 << (local4 == 31) ? (0) : (25 - local4 >> 1);
;
	local5 = 	*(void*)(local3);
	while (1) { // Loop name: 'label$103'
	if (	*(void*)(	local3 = local5;
) & -8 == local0) break;	local5 = local4 >> 29;
	local4 = local4 << 1;
	if (	local5 = 	*(void*)(	local8 = local3 + local5 & 4 + 16;
);
) break;
	} // End of loop 'label$103'
*((void*)(local8) = local6; 
*((void*)(local6) = local3; 
*((void*)(local6) = local6; 
*((void*)(local6) = local6; 
	break;	*((void*)(0) = 	local11 = 	local0 = local2 + -40;
 - 	local8 = (local5 + 8 & 7) ? (-8 - local5 & 7) : (0);
;
;
	*((void*)(0) = 	local8 = local5 + local8;
	*((void*)(local8) = local11 | 1; 
*((void*)(local5 + local0) = 40; 
	*((void*)(0) = 	*(void*)(0); 
*((void*)(	local8 = (local0 < local4 + 16) ? (local4) : (	local0 = local6 + (local6 + -39 & 7) ? (39 - local6 & 7) : (0);
 + -47;
);
;
) = 27; 
	*((void*)(local8 + 16) = 	*(void*)(0); 
	*((void*)(local8) = 	*(void*)(0); 
	*((void*)(0) = local8 + 8; 
*((void*)(0) = local2; 
*((void*)(0) = local5; 
*((void*)(0) = 0; 
	local0 = local8 + 24;
	while (1) { // Loop name: 'label$104'
*((void*)(local0) = 7; 
	local5 = local0 + 8;
	local0 = local0 + 4;
	if (local6 > local5) break;
	} // End of loop 'label$104'
	if (local8 == local4) break;	*((void*)(local8) = 	*(void*)(local8) & -2; 
	*((void*)(local4) = 	local2 = local8 - local4;
 | 1; 
*((void*)(local8) = local2; 
	label$105:
	if (local2 > 255) break;	local0 = 	local6 = local2 >> 3;
 << 3 + 3424;
	label$106:
	label$107:
	if (	local5 = 	*(void*)(0);
 & 	local6 = 1 << local6;
) break;	*((void*)(0) = local5 | local6; 
	local6 = local0;
	break;	local6 = 	*(void*)(local0);
*((void*)(local0) = local4; 
*((void*)(local6) = local4; 
*((void*)(local4) = local0; 
*((void*)(local4) = local6; 
	break;	local0 = 0;
	label$108:
	if (	local6 = local2 >> 8;
 == 0) break;	local0 = 31;
	if (local2 > 16777215) break;	local0 = 	local0 = 	local5 = 	local6 = local6 << 	local0 = local6 + 1048320 >> 16 & 8;
;
 << 	local6 = local6 + 520192 >> 16 & 4;
;
 << 	local5 = local5 + 245760 >> 16 & 2;
 >> 15 - local6 | local0 | local5;
 << 1 | local2 >> local0 + 21 & 1 + 28;
*((void*)(local4) = 0; 
*((void*)(local4 + 28) = local0; 
	local6 = local0 << 2 + 3688;
	label$109:
	label$110:
	if (	local5 = 	*(void*)(0);
 & 	local8 = 1 << local0;
) break;	*((void*)(0) = local5 | local8; 
*((void*)(local6) = local4; 
*((void*)(local4 + 24) = local6; 
	break;	local0 = local2 << (local0 == 31) ? (0) : (25 - local0 >> 1);
;
	local5 = 	*(void*)(local6);
	while (1) { // Loop name: 'label$111'
	if (	*(void*)(	local6 = local5;
) & -8 == local2) break;	local5 = local0 >> 29;
	local0 = local0 << 1;
	if (	local5 = 	*(void*)(	local8 = local6 + local5 & 4 + 16;
);
) break;
	} // End of loop 'label$111'
*((void*)(local8) = local4; 
*((void*)(local4 + 24) = local6; 
*((void*)(local4) = local4; 
*((void*)(local4) = local4; 
	break;*((void*)(	local0 = 	*(void*)(local3);
) = local6; 
*((void*)(local3) = local6; 
*((void*)(local6) = 0; 
*((void*)(local6) = local3; 
*((void*)(local6) = local0; 
	local0 = local11 + 8;
	break;*((void*)(	local0 = 	*(void*)(local6);
) = local4; 
*((void*)(local6) = local4; 
*((void*)(local4 + 24) = 0; 
*((void*)(local4) = local6; 
*((void*)(local4) = local0; 
	if (	local0 = 	*(void*)(0);
 <= local3) break;	*((void*)(0) = 	local4 = local0 - local3;
	*((void*)(0) = 	local6 = 	local0 = 	*(void*)(0);
 + local3;
	*((void*)(local6) = local4 | 1; 
	*((void*)(local0) = local3 | 3; 
	local0 = local0 + 8;
	break;*((void*)(	f12();
) = 48; 
	local0 = 0;
	break;	label$112:
	if (local11 == 0) break;	label$113:
	label$114:
	if (local8 != 	*(void*)(	local0 = 	local4 = 	*(void*)(local8);
 << 2 + 3688;
)) break;*((void*)(local0) = local5; 
	if (local5) break;	*((void*)(0) = 	local7 = local7 & _rotl(-2, local4);
	break;*((void*)(local11 + (	*(void*)(local11) == local8) ? (16) : (20);
) = local5; 
	if (local5 == 0) break;*((void*)(local5) = local11; 
	label$115:
	if (	local0 = 	*(void*)(local8);
 == 0) break;*((void*)(local5) = local0; 
*((void*)(local0) = local5; 
	if (	local0 = 	*(void*)(local8 + 20);
 == 0) break;*((void*)(local5 + 20) = local0; 
*((void*)(local0) = local5; 
	label$116:
	label$117:
	if (local6 > 15) break;	*((void*)(local8) = 	local0 = local6 + local3;
 | 3; 
	*((void*)(	local0 = local8 + local0;
) = 	*(void*)(local0) | 1; 
	break;	*((void*)(local8) = local3 | 3; 
	*((void*)(	local5 = local8 + local3;
) = local6 | 1; 
*((void*)(local5 + local6) = local6; 
	label$118:
	if (local6 > 255) break;	local0 = 	local4 = local6 >> 3;
 << 3 + 3424;
	label$119:
	label$120:
	if (	local6 = 	*(void*)(0);
 & 	local4 = 1 << local4;
) break;	*((void*)(0) = local6 | local4; 
	local4 = local0;
	break;	local4 = 	*(void*)(local0);
*((void*)(local0) = local5; 
*((void*)(local4) = local5; 
*((void*)(local5) = local0; 
*((void*)(local5) = local4; 
	break;	label$121:
	label$122:
	if (	local4 = local6 >> 8;
) break;	local0 = 0;
	break;	local0 = 31;
	if (local6 > 16777215) break;	local0 = 	local0 = 	local3 = 	local4 = local4 << 	local0 = local4 + 1048320 >> 16 & 8;
;
 << 	local4 = local4 + 520192 >> 16 & 4;
;
 << 	local3 = local3 + 245760 >> 16 & 2;
 >> 15 - local4 | local0 | local3;
 << 1 | local6 >> local0 + 21 & 1 + 28;
*((void*)(local5) = local0; 
*((void*)(local5) = 0; 
	local4 = local0 << 2 + 3688;
	label$123:
	label$124:
	label$125:
	if (local7 & 	local3 = 1 << local0;
) break;	*((void*)(0) = local7 | local3; 
*((void*)(local4) = local5; 
*((void*)(local5) = local4; 
	break;	local0 = local6 << (local0 == 31) ? (0) : (25 - local0 >> 1);
;
	local3 = 	*(void*)(local4);
	while (1) { // Loop name: 'label$126'
	if (	*(void*)(	local4 = local3;
) & -8 == local6) break;	local3 = local0 >> 29;
	local0 = local0 << 1;
	if (	local3 = 	*(void*)(	local2 = local4 + local3 & 4 + 16;
);
) break;
	} // End of loop 'label$126'
*((void*)(local2) = local5; 
*((void*)(local5) = local4; 
*((void*)(local5) = local5; 
*((void*)(local5) = local5; 
	break;*((void*)(	local0 = 	*(void*)(local4);
) = local5; 
*((void*)(local4) = local5; 
*((void*)(local5) = 0; 
*((void*)(local5) = local4; 
*((void*)(local5) = local0; 
	local0 = local8 + 8;
	break;	label$127:
	if (local10 == 0) break;	label$128:
	label$129:
	if (local5 != 	*(void*)(	local0 = 	local6 = 	*(void*)(local5);
 << 2 + 3688;
)) break;*((void*)(local0) = local8; 
	if (local8) break;	*((void*)(0) = local9 & _rotl(-2, local6); 
	break;*((void*)(local10 + (	*(void*)(local10) == local5) ? (16) : (20);
) = local8; 
	if (local8 == 0) break;*((void*)(local8) = local10; 
	label$130:
	if (	local0 = 	*(void*)(local5);
 == 0) break;*((void*)(local8) = local0; 
*((void*)(local0) = local8; 
	if (	local0 = 	*(void*)(local5 + 20);
 == 0) break;*((void*)(local8 + 20) = local0; 
*((void*)(local0) = local8; 
	label$131:
	label$132:
	if (local4 > 15) break;	*((void*)(local5) = 	local0 = local4 + local3;
 | 3; 
	*((void*)(	local0 = local5 + local0;
) = 	*(void*)(local0) | 1; 
	break;	*((void*)(local5) = local3 | 3; 
	*((void*)(	local6 = local5 + local3;
) = local4 | 1; 
*((void*)(local6 + local4) = local4; 
	label$133:
	if (local7 == 0) break;	local3 = 	local8 = local7 >> 3;
 << 3 + 3424;
	local0 = 	*(void*)(0);
	label$134:
	label$135:
	if (	local8 = 1 << local8;
 & local2) break;	*((void*)(0) = local8 | local2; 
	local8 = local3;
	break;	local8 = 	*(void*)(local3);
*((void*)(local3) = local0; 
*((void*)(local8) = local0; 
*((void*)(local0) = local3; 
*((void*)(local0) = local8; 
*((void*)(0) = local6; 
*((void*)(0) = local4; 
	local0 = local5 + 8;
	label$136:
	if (local13 = local1 + 16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local13;
local0}
void f53(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	int local3; 
	int local4; 
	int local5; 
	int local6; 
	int local7; 
	label$1:
	if (local0 == 0) break;local3 = local1 = local0 + -8 + local0 = local2 = 	*(void*)(local0 + -4) & -8	label$2:
	if (local2 & 1) break;	if (local2 & 3 == 0) break;	if (local1 = local1 - local2 = 	*(void*)(local1) < local4 = 	*(void*)(0)) break;local0 = local2 + local0		label$3:
		if (		*(void*)(0) == local1) break;			label$4:
			if (local2 > 255) break;local5 = 			*(void*)(local1)				label$5:
				if (local6 = 				*(void*)(local1) == local2 = local7 = local2 >> 3 << 3 + 3424) break;	/* Drop routine */
local4 > local6	/* End of drop routine */
				label$6:
				if (local5 != local6) break;*((void*)(0) = 				*(void*)(0) & _rotl(-2, local7)				break;				label$7:
				if (local5 == local2) break;	/* Drop routine */
local4 > local5	/* End of drop routine */
*((void*)(local6) = local5*((void*)(local5) = local6			break;local7 = 		*(void*)(local1)			label$8:
				label$9:
				if (local5 = 				*(void*)(local1) == local1) break;					label$10:
					if (local4 > local2 = 					*(void*)(local1)) break;	/* Drop routine */
					*(void*)(local2) != local1	/* End of drop routine */
*((void*)(local2) = local5*((void*)(local5) = local2				break;				label$11:
				if (local4 = 				*(void*)(local2 = local1 + 20)) break;				if (local4 = 				*(void*)(local2 = local1 + 16)) break;local5 = 0				break;			while (1) { // Loop name: 'label$12'
local6 = local2			if (local4 = 			*(void*)(local2 = local5 = local4 + 20)) break;local2 = local5 + 16			if (local4 = 			*(void*)(local5)) break;
		} // End of loop 'label$12'
*((void*)(local6) = 0	if (local7 == 0) break;		label$13:
			label$14:
			if (			*(void*)(local2 = local4 = 			*(void*)(local1) << 2 + 3688) != local1) break;*((void*)(local2) = local5			if (local5) break;*((void*)(0) = 			*(void*)(0) & _rotl(-2, local4)			break;*((void*)(local7 + (		*(void*)(local7) == local1) ? (16) : (20);
) = local5		if (local5 == 0) break;*((void*)(local5) = local7		label$15:
		if (local2 = 		*(void*)(local1) == 0) break;*((void*)(local5) = local2*((void*)(local2) = local5	if (local2 = 	*(void*)(local1) == 0) break;*((void*)(local5 + 20) = local2*((void*)(local2) = local5	break;	if (local2 = 	*(void*)(local3) & 3 != 3) break;*((void*)(0) = local0*((void*)(local3) = local2 & -2*((void*)(local1) = local0 | 1*((void*)(local1 + local0) = local0	return;
	if (local3 <= local1) break;	if (local2 = 	*(void*)(local3) & 1 == 0) break;	label$16:
	label$17:
	if (local2 & 2) break;		label$18:
		if (		*(void*)(0) != local3) break;*((void*)(0) = local1*((void*)(0) = local0 = 		*(void*)(0) + local0*((void*)(local1) = local0 | 1		if (local1 != 		*(void*)(0)) break;*((void*)(0) = 0*((void*)(0) = 0		return;
		label$19:
		if (		*(void*)(0) != local3) break;*((void*)(0) = local1*((void*)(0) = local0 = 		*(void*)(0) + local0*((void*)(local1) = local0 | 1*((void*)(local1 + local0) = local0		return;
local0 = local2 & -8 + local0		label$20:
			label$21:
			if (local2 > 255) break;local4 = 			*(void*)(local3)				label$22:
				if (local5 = 				*(void*)(local3) == local2 = local3 = local2 >> 3 << 3 + 3424) break;	/* Drop routine */
				*(void*)(0) > local5	/* End of drop routine */
				label$23:
				if (local4 != local5) break;*((void*)(0) = 				*(void*)(0) & _rotl(-2, local3)				break;				label$24:
				if (local4 == local2) break;	/* Drop routine */
				*(void*)(0) > local4	/* End of drop routine */
*((void*)(local5) = local4*((void*)(local4) = local5			break;local7 = 		*(void*)(local3)			label$25:
				label$26:
				if (local5 = 				*(void*)(local3) == local3) break;					label$27:
					if (					*(void*)(0) > local2 = 					*(void*)(local3)) break;	/* Drop routine */
					*(void*)(local2) != local3	/* End of drop routine */
*((void*)(local2) = local5*((void*)(local5) = local2				break;				label$28:
				if (local4 = 				*(void*)(local2 = local3 + 20)) break;				if (local4 = 				*(void*)(local2 = local3 + 16)) break;local5 = 0				break;			while (1) { // Loop name: 'label$29'
local6 = local2			if (local4 = 			*(void*)(local2 = local5 = local4 + 20)) break;local2 = local5 + 16			if (local4 = 			*(void*)(local5)) break;
		} // End of loop 'label$29'
*((void*)(local6) = 0	if (local7 == 0) break;		label$30:
			label$31:
			if (			*(void*)(local2 = local4 = 			*(void*)(local3) << 2 + 3688) != local3) break;*((void*)(local2) = local5			if (local5) break;*((void*)(0) = 			*(void*)(0) & _rotl(-2, local4)			break;*((void*)(local7 + (		*(void*)(local7) == local3) ? (16) : (20);
) = local5		if (local5 == 0) break;*((void*)(local5) = local7		label$32:
		if (local2 = 		*(void*)(local3) == 0) break;*((void*)(local5) = local2*((void*)(local2) = local5	if (local2 = 	*(void*)(local3) == 0) break;*((void*)(local5 + 20) = local2*((void*)(local2) = local5*((void*)(local1) = local0 | 1*((void*)(local1 + local0) = local0	if (local1 != 	*(void*)(0)) break;*((void*)(0) = local0	return;
*((void*)(local3) = local2 & -2*((void*)(local1) = local0 | 1*((void*)(local1 + local0) = local0	label$33:
	if (local0 > 255) break;local0 = local2 = local0 >> 3 << 3 + 3424	label$34:
	label$35:
	if (local4 = 	*(void*)(0) & local2 = 1 << local2) break;*((void*)(0) = local4 | local2local2 = local0	break;local2 = 	*(void*)(local0)*((void*)(local0) = local1*((void*)(local2) = local1*((void*)(local1) = local0*((void*)(local1) = local2	return;
local2 = 0	label$36:
	if (local4 = local0 >> 8 == 0) break;local2 = 31	if (local0 > 16777215) break;local2 = local2 = local5 = local4 = local4 << local2 = local4 + 1048320 >> 16 & 8 << local4 = local4 + 520192 >> 16 & 4 << local5 = local5 + 245760 >> 16 & 2 >> 15 - local4 | local2 | local5 << 1 | local0 >> local2 + 21 & 1 + 28*((void*)(local1) = 0*((void*)(local1 + 28) = local2local4 = local2 << 2 + 3688	label$37:
	label$38:
	label$39:
		label$40:
		if (local5 = 		*(void*)(0) & local3 = 1 << local2) break;*((void*)(0) = local5 | local3*((void*)(local4) = local1*((void*)(local1 + 24) = local4		break;local2 = local0 << (local2 == 31) ? (0) : (25 - local2 >> 1);
local5 = 	*(void*)(local4)	while (1) { // Loop name: 'label$41'
	if (	*(void*)(local4 = local5) & -8 == local0) break;local5 = local2 >> 29local2 = local2 << 1	if (local5 = 	*(void*)(local3 = local4 + local5 & 4 + 16)) break;
	} // End of loop 'label$41'
*((void*)(local3) = local1*((void*)(local1 + 24) = local4*((void*)(local1) = local1*((void*)(local1) = local1	break;*((void*)(local0 = 	*(void*)(local4)) = local1*((void*)(local4) = local1*((void*)(local1 + 24) = 0*((void*)(local1) = local4*((void*)(local1) = local0*((void*)(0) = local1 = 	*(void*)(0) + -1	if (local1) break;local1 = 3840	while (1) { // Loop name: 'label$42'
local1 = local0 = 	*(void*)(local1) + 8	if (local0) break;
	} // End of loop 'label$42'
*((void*)(0) = -1}
void f54(int local0, int local1) {
	label$1:
	if (	*(void*)(0)) break;*((void*)(0) = local1*((void*)(0) = local0}
int f55(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	label$1:
		label$2:
		if (local0 == 0) break;			label$3:
			if (			*(void*)(local0) > -1) break;			return 			f56(local0);
;
local1 = 		f10(local0);
local2 = 		f56(local0);
		if (local1 == 0) break;		f11(local0);
		return local2;
local2 = 0		label$4:
		if (		*(void*)(0) == 0) break;local2 = 		f55(		*(void*)(0));
		label$5:
		if (local0 = 		*(void*)(		f35();
) == 0) break;		while (1) { // Loop name: 'label$6'
local1 = 0			label$7:
			if (			*(void*)(local0) < 0) break;local1 = 			f10(local0);
			label$8:
			if (			*(void*)(local0) <= 			*(void*)(local0)) break;local2 = 			f56(local0);
 | local2			label$9:
			if (local1 == 0) break;			f11(local0);
		if (local0 = 		*(void*)(local0)) break;
	} // End of loop 'label$6'
	f36();
local2}
int f56(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	label$1:
	if (	*(void*)(local0) <= 	*(void*)(local0)) break;	/* Drop routine */
// Indirect call:
(	*(void*)(local0))(local0, 0, 0); 
	/* End of drop routine */
	if (	*(void*)(local0)) break;	return -1;
	label$2:
	if (local1 = 	*(void*)(local0) >= local2 = 	*(void*)(local0)) break;	/* Drop routine */
// Indirect call:
(	*(void*)(local0))(local0, (long)local1 - local2, 1); 
	/* End of drop routine */
*((void*)(local0) = 0*((void*)(local0) = 0*((void*)(local0) = 00}
void f57(int local0) {
	global$2 = local0;
}
int f58() {
global$0}
int f59(int local0) {
	// Parsed WASM function locals:
	int local1; 
	int local2; 
	label$1:
	if (local2 = local1 = global$0 - local0 & -16 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local2;
local1}
void f60(int local0) {
	// Parsed WASM function locals:
	int local1; 
	if (local1 = local0 < global$2) {
	ffimport$5();

	} // <No else block>
	global$0 = local1;
}
int f61(int local0) {
/* Host call */
host_grow_memory(local0)}
int f62(int local0, int local1, double local2, int local3, int local4, int local5, int local6) {
// Indirect call:
(local0)(local1, local2, local3, local4, local5, local6); 
}
void f63(int local0, int local1, int local2) {
// Indirect call:
(local0)(local1, local2); 
}
int f64(int local0, int local1) {
// Indirect call:
(local0)(local1); 
}
int f65(int local0, int local1, int local2, int local3) {
// Indirect call:
(local0)(local1, local2, local3); 
}
long f66(int local0, int local1, long local2, int local3) {
// Indirect call:
(local0)(local1, local2, local3); 
}
int f67(int local0, int local1, int local2, int local3, int local4) {
	// Parsed WASM function locals:
	long local5; 
	local5 = 	f66(local0, local1, (long)local2 | (long)local3 << 32, local4);
;
	ffimport$6((int)local5 >> 32);
(int)local5}
